### ISSUE TITLE
Add thingspeak to code

### ISSUE THREAD

**Issue by rforouzesh** [toblum/McLighting#100]
Hi
I added thingspeak to the code for sending dht11 temp to site
when i add the code WiFiClient  client;
mclighting web server will not work!
in setup i should use the code 
ThingSpeak.begin(client);
what i can use?
Thanks

**Comment by toblum** [comment]
Hi @rforouzesh,

McLighting uses an own WiFiClient if you have MQTT enabled, it's named espClient. Have a look here: https://github.com/toblum/McLighting/blob/24b5e2895091bef27c65a02be0b2344ab551e2e6/Arduino/McLighting/McLighting.ino#L31

So ThingSpeak.begin(espClient); should ork.

Regards
Tobias
