### ISSUE TITLE
Passing multiple parameters via RestAPI in a single GET call

### ISSUE THREAD

**Issue by synssins** [toblum/McLighting#103]
Is this possible? If so, what would the correct URL format be for setting a color before selecting a mode such as Static?

**Comment by toblum** [comment]
H @synssins,

for some named modes (like ALL) it's possible. This sets color to red for example: 
http://MCLIGHTING_URL/all?rgb=FF0000

Regards
Tobias

**Comment by synssins** [comment]
Thanks for the prompt response. I figured it out a few minutes ago. I assume that works for all named modes that use whatever static color was assigned?

**Comment by toblum** [comment]
Hi,
yes, this should work for all named modes that use colors.
Regards
