### ISSUE TITLE
web page not found

### ISSUE THREAD

**Issue by ErfanDL** [toblum/McLighting#11]
Hi. I upload the code to esp8266 but when I open esp8266 IP with browser get error

File Not Found

URI: /
Method: GET
Arguments: 0

please help for fix this problem

**Comment by toblum** [comment]
Dear @ErfanDL,
I think the step "Uploading the webpage" is missing.
See here: https://github.com/toblum/McLighting/wiki/Software-installation#upload-the-webpage-to-the-spiffs-filesystem

Regards
Tobias

**Comment by ErfanDL** [comment]
Thanks. Problem is solved
