### ISSUE TITLE
Set brightness issue

### ISSUE THREAD

**Issue by JCL1977** [toblum/McLighting#112]
Hi toblum,

really a great project - have already three devices running and integrated in my openHAB setup. 

BIG thanks

i think i found a issue: every time i set the brightness with a HTTP REST API request while a program is already running the strip turn's off.... you can turn the program on again and the brightness did change. 

Doing it with the webinterface works like a charme...

I could turn it on again with my openHAB, but i think you don't planned it that way on purpose?

If you have some time, it would be great to get it fixed

Thanks
Jens

**Comment by toblum** [comment]
Hi Jens,

you're right, this behavior is not expected. I changed the code so that it doesn't switch back to single color mode. Just pull the latest version. There are just tree lines deleted.

Regards
Tobias
