### ISSUE TITLE
Latest WS2812FX Breaks McLighting?

### ISSUE THREAD

**Issue by ke5** [toblum/McLighting#113]
I just updated WS2812FX (downloaded the .zip from github) and rebuilt the latest McLighting master branch. All appeared to work correctly until I tried to load the web interface. It just hangs, looks like it's trying to read the list of modes. WS2812FX has recently added an extra 'custom' mode, could this be the problem? Anyone else experiencing the same? I've tried various configurations (NodeMCU, Wemos D1 Mini) and numbers of LEDS.
Am I missing something or, more likely, done something foolish?

**Comment by ke5** [comment]
I should add, I reverted to the previous WS2812FX library (thank goodness I save it!) and all works perfectly.

**Comment by debsahu** [comment]
I used latest WS2812FX, did not notice any issues.

**Comment by ke5** [comment]
I did a complete reinstall of the IDE, ESP8266 core and libraries, rebuilt and now everything is working nominally. Clearly, the problem was with my environment and not with WS2812FX or McLighting. Thanks for your help, I appreciate you taking the time to look into it.
