### ISSUE TITLE
Errir When NUMLEDS below 5

### ISSUE THREAD

**Issue by ItownTech** [toblum/McLighting#114]
I used wemos D1 mini and one ws2812, when i set NUMLEDS below 5 in definitions.h，the D1 mini will be crashed , and show error meaasges by serial console：

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld

**Comment by debsahu** [comment]
I can't replicate this. I used 4 and it's running just fine.

**Comment by ItownTech** [comment]
I used NUMLEDS above 6 and it's running just fine. below 5 and it crash.

**Comment by toblum** [comment]
HI @ItownTech,

it's the same here: Works with the same with 3 as with 300 LEDs set. Also tried on a D1 mini clone. Not able to reproduce this. Seems to be related to your specific environment. Hard to debug.

Is this a problem for you? You should be able to set it to 5 even with only one LED connected. This shouldn't make any noticeable difference in usage.

Regards
Tobias

**Comment by ItownTech** [comment]
hi @toblum

yes, i must set it to 5 even with only one LED connected. otherwise it will crash.

**Comment by ItownTech** [comment]
hi @toblum

i make some tests, and i found when i connect wi-fi, it will crash, then i disconnect wi-fi , it worked fine.

**Comment by ItownTech** [comment]
I solved this problem. It wasn't a BUG. After I updated the ArduinoJson.h to the last version, It's running fine.
