### ISSUE TITLE
Tipp for SPIFFS upload

### ISSUE THREAD

**Issue by wunderbaum** [toblum/McLighting#115]
Hello!
To get the spiffs-data more easily on the device there is a plugin for Arduino:
[https://github.com/esp8266/arduino-esp8266fs-plugin](https://github.com/esp8266/arduino-esp8266fs-plugin)

**Comment by toblum** [comment]
Thank you @wunderbaum,

I knew that plugin too, but found uploading via web always a bit easier. But I added a note to the Wiki, that this can be used alternatively.
