### ISSUE TITLE
Missing Credentials for AMQTT

### ISSUE THREAD

**Issue by Bl4cksh4rk1990** [toblum/McLighting#130]
Hello,

i have tested your new Version of McLighting.
When i need username and password to login we want to add

amqttClient.setCredentials(mqtt_user, mqtt_pass);

**Comment by debsahu** [comment]
You are right, I totally forgot to add that.

**Comment by debsahu** [comment]
I have pushed the update here: https://github.com/toblum/McLighting/pull/129 Once I get a chance to test it, I will merge it. For now could you test https://github.com/debsahu/McLighting/ ?
