### ISSUE TITLE
/set_mode?m=2&rgb=0000AA&s=200 will not set color, but mode

### ISSUE THREAD

**Issue by bpohvoodoo** [toblum/McLighting#132]
insert
    strip.setColor(main_color.red, main_color.green, main_color.blue);
before 
    strip.setMode(ws2812fx_mode)
on line 911
of code Mclighting.ino
will correct this behaviour

or better
  if (mode == SET_MODE) {
    DBG_OUTPUT_PORT.printf("SET_MODE: %d %d\n", ws2812fx_mode, mode);
    strip.setColor(main_color.red, main_color.green, main_color.blue);
    strip.setMode(ws2812fx_mode);
    strip.setSpeed(convertSpeed(ws2812fx_speed));
    mode = HOLD;
  }

**Comment by debsahu** [comment]
Thanks for RGBW branch, does my fixes solve this issue?

**Comment by bpohvoodoo** [comment]
I'm shure it does. ;-)
 I have updated my brach regarding to this post.
