### ISSUE TITLE
Modes Page Reverts Color

### ISSUE THREAD

**Issue by ryancasler** [toblum/McLighting#133]
When I open the second pane on the webpage for mode selection, it always reverts back to RGB 128,128,128.  The brightness and speed sliders don't match what is currently running on the strip but they don't "hijack" what is already running at least.  But, for example, I initiate a group of settings from another source.  Now i want to go in and dim them more, i can't do that since the slider is only on the 2nd page and I'll lose my color setting.  Any assistance you could give me would be greatly appreciated.  Removing 
	
```
if (pane == "pane2") {
			setMainColor();
		}

```
from the html file seems to solve the problem.

**Comment by ryancasler** [comment]
I see a lot of movement on the project.  Anything on this?

**Comment by toblum** [comment]
Not yet, creating a complete new UI takes time (I also have to learn a new framework). Expect more weeks than days for the first results.

**Comment by toblum** [comment]
@ryancasler PLease have a look here: https://github.com/toblum/McLightingUI/

Regards
Tobias

**Comment by ryancasler** [comment]
Will do when I'm back home this weekend.

**Comment by ryancasler** [comment]
Very confused.  All I have to do is upload the index2.html file?  And then what?  Do I delete the old one?

**Comment by debsahu** [comment]
You can enter http://<IP>/index2.html and check if that version works. I can confirm it does! If you are satisfied, delete both files on the SPIFFs and rename index2.html on your computer to index.html and upload it.

**Comment by chkbln** [comment]
Hi debsahu,
can you tell me how to delete files in the SPIFFs?
Thanks and best regards

**Comment by debsahu** [comment]
@chkbln Using Arduino IDE, goto Tools -> Erase Flash -> All flash contents and flash McLighting.

**Comment by LeonVos** [comment]
In sketch you can do;
SPIFFS.format();

**Comment by chkbln** [comment]
I was hoping to delete files via Edit

![grafik](https://user-images.githubusercontent.com/11814828/40588955-c411ff08-61e5-11e8-9c36-29dcb1d1053a.png)
