### ISSUE TITLE
After reboot ip automatically changing

### ISSUE THREAD

**Issue by BoSsOfDMaX** [toblum/McLighting#14]
What should i do to put static ip

Just an idea, Can i change the ip adress to hostname like 192.168.1.102 to www.esp8266dsgn.com

Regards

**Comment by toblum** [comment]
Hi @BoSsOfDMaX,

setting an Hostname as IP is not possible. But McLighting implements Bonjour, so you could call it by its name, if you have Bonjour installed.

Some Wifi routers also have the possibility to set a name for a device or to fix the IP adress.

You could also try to set a static IP according to this example: https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithStaticIP/AutoConnectWithStaticIP.ino

Regards
Tobias
