### ISSUE TITLE
McLightning Hostanem with Esp-Chip-Id

### ISSUE THREAD

**Issue by TechOnlyGamer** [toblum/McLighting#149]
Hey Guys is there an easy Way to implement that the Hostanme of the Esp matches something like McLightning-*chip-id*
So if we get more than One esp in the house we dont have to change the Hostname everytime we create a new binary for upload. Someone could implement it????maybe in config to choose between normal mclightning01 and the hostname method? thanks

**Comment by debsahu** [comment]
Should be easy, later today afternoon. Will you be able to test it?

**Comment by TechOnlyGamer** [comment]
sure as iam working on a seconf esp on my desk i will test the feature asap so everything should be easier even the homeassistant discover name maybe?

**Comment by debsahu** [comment]
@TechOnlyGamer Try my version as see if it works? look for #define ENABLE_HA_HOSTNAME_CHIPID and/or #define ENABLE_MQTT_HOSTNAME_CHIPID to add chipID to hostname. By default it adds chip ID to MQTT hostname and disabled for HA.

**Comment by TechOnlyGamer** [comment]
i am looking at it right now but i dont really understand what u mean with ha hostname and mqtt hostname. i though about changing the hole Esp Hostname variable to McLightning+ESP Id so everything like mqtt setup topic etc would change....can u explain what each hostname mean??

**Comment by debsahu** [comment]
The value in **HOSTNAME** is what is used as a base for everything.

`const char HOSTNAME[] = "McLighting01";`

* If `#define ENABLE_HA_HOSTNAME_CHIPID` is uncommented,
HA autodiscovery will have a hostname of "McLighting01-7982398" where 7982398 is Chip ID
If `//#define ENABLE_HA_HOSTNAME_CHIPID` is commented,
HA autodiscovery will have a hostname of "McLighting01"

* If `#define ENABLE_MQTT_HOSTNAME_CHIPID` is uncommented,
MQTT client name will have a hostname of "McLighting01-7982398" where 7982398 is Chip ID
If `//#define ENABLE_MQTT_HOSTNAME_CHIPID` is commented,
MQTT client name will have a hostname of "McLighting01"

**Comment by TechOnlyGamer** [comment]
ok got it thanks its working fine but setting it up in ha without knewing the chip id first its a little bit useless as u could change the friendly hostname to something diffrent and it works also. thanks for ur work but i dont know if we need to keep it ??

**Comment by debsahu** [comment]
I agree.
