### ISSUE TITLE
Unable to compile after all libraries are installed.

### ISSUE THREAD

**Issue by Fireflaker** [toblum/McLighting#15]
In file included from C:\Users\win7\Desktop\EE\WS2812LED\McLighting-master\Arduino\McLighting\McLighting.ino:97:0:

sketch\request_handlers.h: In function 'char* listStatusJSON()':

sketch\request_handlers.h:84:8: warning: address of local variable 'json' returned [-Wreturn-local-addr]

   char json[255];

        ^

C:\Users\win7\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(const char*, uint16_t, const char*, const char*)':

C:\Users\win7\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp:69:16: error: 'RANDOM_REG32' was not declared in this scope

     randomSeed(RANDOM_REG32);

                ^

What does it mean? How can I solve it? 
Is "RANDOM" function not available?
Please help. Thank you.

**Comment by toblum** [comment]
Hi @Fireflaker,

these error messages seem to be related with older versions of the Arduino core: https://goo.gl/Ktw1QY. What version do you use? Is there a update available in the board manager?

Regards
Tobias

**Comment by Fireflaker** [comment]
Thank you so much. Problem solved.

**Comment by toblum** [comment]
You're welcome
