### ISSUE TITLE
Which GPIO to use on a PCB?

### ISSUE THREAD

**Issue by codmpm** [toblum/McLighting#155]
As I'm designing a new revision of my NeoPixel-Driver-Booard (https://allgeek.de/2018/01/29/esp8266-neopixel-controller/ - german) I wanted to know, which pins I should support now.
I'm think of a solder jumper or something else, to make it switchable for the user.

Currently I'm using GPIO5, which is suitable for WS2812FX and the Adafruit NeoPixel library. As NeoAnimationFX got intruduced we now have more options. It can use the DMA method via GPIO3 and the UART method via GPIO2.

Should we only need these three pins (GPIO5 is interchangeable as I understand) or are there options for other ones?

Cheers,
Patrik

**Comment by debsahu** [comment]
If you had to choose only one pin, I would choose GPIO2. As one can define the pin for WS2812FX library and pin is ignored for NeoAnimationFX, chosen by the method used (NeoPBBGRBU800).

But I prefer the idea of solder jumper and break out all the three you mentioned. What I have is a physical jumper that I can switch between GPIO2(WS2812FX/NeoAnimationFX-UART) and GPIO3 (NeoAnimationFX-DMA).

Btw I like your choice of voltage regulator, it's it better than HT7333-A?

**Comment by debsahu** [comment]
I noticed that you are using RGBW strips in your blog, NeoAnimationFX doesn't support it for now!

**Comment by codmpm** [comment]
Hey @debsahu, thank you for your reply ^^

I've read already, that RGBW is not supported by NeoAnimationFX yet, so I will stick with the Adafruit Lib. 
But as I was asked if I wanted to sell some modules and thus had to do a new batch and thought, why not revise the board... so at best everyone can use their prefered stripe, library or pin ;-)

I'm currently searching for a 4 pin solder jumper, which is of course difficult. I'm not sure if I want to use a classical through hole Jumper with headers.

By the way, does using GPIO3 (RX) interfere with programming in any way?

I'm using the [AP2210](https://www.diodes.com/assets/Datasheets/AP2210.pdf) in many other 3.3V application and, in comparison to the HT7333, it is sourceable through digikey (e.g).
So primarily I choosed this LDO as I had it laying around :-)

**Comment by debsahu** [comment]
Yeah finding 3 pin solder jumper is easier that's why I suggested GPIO2 and 3.

Regarding use of GPIO3, it is the other way around. While flashing ESP8266 one will notice flashing of LEDs.

Regarding the capacitors used with AP2210, to you think bumping the one on 3.3V one to 1000uF SMD is a good choice? Sometimes the peak power draw of ESP8266 will exceed the 300mA provided by the LDO.

**Comment by codmpm** [comment]
If GPIO2 is useable is usable with the Adafruit library, than there should be no problem with only two choices 👍 

Well, if someone wants to use DMA mode (GPIO3/RX) it should be ok, as programming maybe will be done without connected LEDs. Hopefully everyone will use OTA in finished installation.

I don't know if I got you right, which capacitor should get bumped to 1000µF? https://allgeek.de/wp-content/uploads/2018/01/esp8266-neopixel-controller-0.3.png
C3 is 1000µF as mentioned is the Adafruit UberGuide and on the 5V side...

**Comment by debsahu** [comment]
I meant C2. I think the current one is fine if the router is close, ESP 8266 current draw increases as the distance from router increases.

**Comment by codmpm** [comment]
I have problems with powering the ESP if used together with sensor hardware (CCS811, etc) - namely random and wdt resets. 
Maybe, if it's ok, you can contact me via blog@allgeek.de so I can shoot some questions in your direction?

**Comment by debsahu** [comment]
Sure I'll shoot you an email. By "router" I mean the AP that ESP8266 connects to.

**Comment by debsahu** [comment]
@codmpm Also have you seen the BME680? A decent replacement for CCS811.

**Comment by codmpm** [comment]
Ah, the Wi-Fi router.. I see..

I will get to you by email, as the chatting does not have anything to do with the issue 😀

**Comment by codmpm** [comment]
Just for followup: There's a 600mA Version of the mentioned LDO: AP2112
https://www.diodes.com/assets/Datasheets/AP2112.pdf

**Comment by debsahu** [comment]
Sorry that I missed your email. Yeah that is a great LDO, I also recently came across HT7833 (a successor to HT7333) ~500mA.

**Comment by codmpm** [comment]
Oh, that one looks nice indeed. 
Don't mind missing the mail :-)

**Comment by debsahu** [comment]
@codmpm you might be interested in these:
https://easyeda.com/debsahu/McLighting
https://easyeda.com/debsahu/mclightingnodemcudip
https://easyeda.com/debsahu/mclightingnodemcu

**Comment by codmpm** [comment]
These are nice!!! Did I inspire you with my desgin? ;-)

Btw, there are one-channel line driver: 74HCT1G125 or 74LVC1G125
Both should work, did not had time to test these.

**Comment by debsahu** [comment]
@codmpm I had McLighting circuit designed already, and of course was inspired by your layout for PCB design. I made these public recently. The 5V tracks are 25mil (even the Chinese use American/Imperial units and not SI, blows my mind), you think I should double it or something? I never knew about single channel 3.3V to 5V level shifter, I'll look into these. Do these handle 800/400kHz ws2812 signal efficiently, I mean timing wise?

**Comment by codmpm** [comment]
Hm. I'm currently testing the AP2112... it can only take 6.0V max... im comparison the AP2210 can be fed with up to 13.2V... the HT7833 can manage 8 Volts... 

For a 5V application the AP2112 should be ok. I will test the stability...
