### ISSUE TITLE
Http Request mode or colors?

### ISSUE THREAD

**Issue by gabenthegamer** [toblum/McLighting#156]
Is there a way to request modes or colors with the api? With commands or post requests

**Comment by debsahu** [comment]
Details are in the wiki https://github.com/toblum/McLighting/wiki/HTTP-REST-API

**Comment by gabenthegamer** [comment]
I see that but how do i change the {"mode":1, "ws2812fx_mode":0, "ws2812fx_mode_name":"Static", "speed":196, "brightness":196, "color":[255, 0, 66]} How do i change the mode with example CMD or whatever program?

**Comment by gabenthegamer** [comment]
Thanks! Got it to work now :D

**Comment by toblum** [comment]
@j0hncc Thanks for pointing me to this. I added the missing parameters.

Regards
Tobias
