### ISSUE TITLE
WiPy (micropython) version ? 

### ISSUE THREAD

**Issue by arthurlutz** [toblum/McLighting#158]
Hi, 

The project looks awesome, congrats on glue together all these technologies and libraries. 

Anyone interested in working on a wipy (pycom) micropython version of this library ?

**Comment by toblum** [comment]
Hi @arthurlutz,

Micropython looks interesting. I did some simple tests some time ago. Looks promising.

Maybe you can find someone who enjoys doing something like this.

Best regards
Tobias
