### ISSUE TITLE
'class Ticker' has no member named 'active'

### ISSUE THREAD

**Issue by Derodin** [toblum/McLighting#159]
Hello,

if i Check the Stetch give me a Error:
`McLighting:777:31: error: 'class Ticker' has no member named 'active'`
on more lines

This is on a Error line to find:
`if(!spiffs_save_state.active()) spiffs_save_state.once(3, tickerSpiffsSaveState);`

who can this error fix?

**Comment by debsahu** [comment]
Update your arduino-esp8266 core to v2.4.1

**Comment by Derodin** [comment]
again Thanks :)

I still do not quite look through with the modes where exactly can I add which? As an example for a new modes is I have 300 LEDs, but only those between 150 to 200 LED light up with new Button: PC-Table

**Comment by Derodin** [comment]
Thanks again :)
