### ISSUE TITLE
How to add more libraries for countrolling the LED as a matrix?

### ISSUE THREAD

**Issue by Fireflaker** [toblum/McLighting#17]
Thank you very much for this fantastic code!

I am trying to add in the FastLED library to control a 10x10 WS2812  LED panel. Such function could be useful to display text input from the Http server, from an online value or just read analog value from ADC to display.

How can I modify the server page to get everything to work?

**Comment by toblum** [comment]
Switching to FastLED would require changes in several places of the code and would take much time that I currently don't have. :-/
Regarding LEDMatrix there is a project by other users who ported Artnet support to McLighting: https://plus.google.com/+DanBendavid/posts/C5SRUsY8BVJ There is also a special branch in this repository with the code.
