### ISSUE TITLE
STATIC LEDs are Crazy.

### ISSUE THREAD

**Issue by carlymx** [toblum/McLighting#173]
Hello

I have acquired a [nodeMcu module ESP8266 esp-12e](https://es.aliexpress.com/item/1pcs-Wireless-module-NodeMcu-Lua-WIFI-V3-ch340-CH340G-Internet-Things-development-board-based-ESP8266-esp/32794134144.html) and a [strip of leds WS2812B of 4mts 60leds/m](https://es.aliexpress.com/item/1m-4m-5m-WS2812B-Smart-led-pixel-strip-Black-White-PCB-30-60-144-leds-m/2036819167.html?spm=a2g0s.9042311.0.0.633263c0VhyFPU).

I followed the detailed steps in the WIKI and the videos religiously and at first everything works well less for a detail.

The LEDs become "crazy". You order a static color and it takes a while to react and then they begin to blink, you put another color and they do the same ... putting an effect is completely impossible since it does not look anything like what would have to happen.

I have tried a thousand times to load again, reinstall all libraries ... with 10/15/20/80 leds and always do the same, changed the power supply.

I've also tried to change the Digital IO, and I've tried the sketch blick which works perfectly ...

Please help me. What I can be doing wrong...?

[![01](https://i.imgur.com/RGUfVfO.png)](https://i.imgur.com/RGUfVfO.png)

[![02](https://i.imgur.com/cc8UHH1.png)](https://i.imgur.com/cc8UHH1.png)

[![" VIEW GIF HERE "](https://media.giphy.com/media/4HcLJR6grHFj6tNvnI/giphy.gif)](https://gph.is/2JgZoEZ) (I do not know why the gif is not embedded well)

**Comment by debsahu** [comment]
You need a good power supply, I suspect there is lots of noise in your 5V power line. Usually adding a few different capacitors in parallel would resolve this issue. Also are you using a level shifter to send data?

**Comment by petertayloruk** [comment]
What amp power supply do you have? 

⁣Sent from Blue ​

**Comment by carlymx** [comment]
Thank you very much for answering.

When I read the comments I realized that I was using a 9V 200mA power supply with a [voltage regulator at 5V and 3.3V](https://es.aliexpress.com/store/product/MB102-Breadboard-Power-Supply-Module-3-3V-5V-For-Arduino-Solderless-Breadboard/1414081_2038557602.html?spm=a219c.search0104.3.1.5cb01810ks4tuf&ws_ab_test=searchweb0_0,searchweb201602_4_10152_10151_10065_10344_10068_10342_10547_10343_10340_10548_10341_10696_10084_5722520_10083_10618_10307_10820_10301_10821_10303_10059_5722620_5722920_5722720_5722820_100031_10103_10624_10623_10622_10621_10620,searchweb201603_25,ppcSwitch_5&algo_expid=96307a3c-ec58-41f2-ae6a-789b8652566d-0&algo_pvid=96307a3c-ec58-41f2-ae6a-789b8652566d&priceBeautifyAB=0).

Provide a PC source with direct supply of the yellow cable (5V) to the LED strip and the 3.3v controller for the ESP8266 and the same thing happened to me ... It could not be, a PC source giving problems ...

I tried with several chargers for mobile 5V-2.5A and 5V-1A with total success, check all the ESP8266 models that I have and without problems.

![https://i.imgur.com/9E0PyTO.jpg](https://i.imgur.com/9E0PyTO.jpg)

Saying that 22 leds + the ESP module consume an average of 220mA as shown by the Ammeter.

![https://i.imgur.com/UaRuBQO.jpg](https://i.imgur.com/UaRuBQO.jpg)

Thank you very much for the help.
