### ISSUE TITLE
SOLUTION: Lack of Space in ESP-01 to compile MCLighting

### ISSUE THREAD

**Issue by carlymx** [toblum/McLighting#179]
Hi.

With reference to the question I asked in #175 about the fact that the Sketch was currently 104% of the total memory available in an ESP8266 ESP-01 (512KB (64KB SPIFFS)) and therefore does not fit, and does not let it continue.

It occurred to me that I could re-partition the flash memory and grant more space available for the Sketch. Specifically after several days with the hexadecimal calculator, I managed to modify the memory to have a total of 480KB for Sketch and 32KB for SPIFFS (Total 512KB).

With 32KB it is enough to upload the contents of the ```".\Data\"``` directory and the Index.html without problems.

![img](https://raw.githubusercontent.com/carlymx/SPIFFS-Mod-for-ESP8266/master/imgs/upload_sketch.png)

I hope it works for you and if you think it is convenient you can indicate it on your Wiki for all those people who want to compile the program within an ESP-01.

The Repository I have hosted here:
### [https://github.com/carlymx/SPIFFS-Mod-for-ESP8266](https://github.com/carlymx/SPIFFS-Mod-for-ESP8266)

**Comment by toblum** [comment]
Hi @carlymx,

thank you for figuring this out. This will help ESP-01 users a lot. I linked you page from the wiki: https://github.com/toblum/McLighting/wiki/Software-installation

Best regards
Tobias
