### ISSUE TITLE
White variations and basic colour pick

### ISSUE THREAD

**Issue by pozek** [toblum/McLighting#18]
Hi Tobias, first of all I want to say thank you for this code.
I was wander if it's posible to integrate a third pane in web page or in wheel pane to select basic colours and white variations (very useful) as described in this link : [http://planetpixelemporium.com/tutorialpages/light.html](url)
Thank you very much !

**Comment by toblum** [comment]
Dear @pozek,

your should be able to implement this by adapting the HTML Frontend here: https://github.com/toblum/McLighting/blob/master/clients/web/build/index.htm
and uploading it to the McLighting.

Regards
Tobias
