### ISSUE TITLE
Add called command in Websocket response?

### ISSUE THREAD

**Issue by codmpm** [toblum/McLighting#19]
First off, thank you for a WS2812 controller with an dedicated API!

It would be nice to have the issued command in the response of the websocket message. Something like `#ok` or `color:ok`.

Right now it kind of difficult to distinguish between an answer to a command or if you just polled for the current status. Or did I miss something?

Cheers,
Patrik

**Comment by toblum** [comment]
Hi Patrik,

This sounds useful. I will have a look at it as soon as I find time. Or you could file a pull request if you already have something. 

Regards 
Tobias

**Comment by codmpm** [comment]
Sadly not. Did not do a deep dive into code, yet ;-)

I have some more question, maybe you can get back to me. Alreay tried to reach out to you via FB.

Cheers.

**Comment by codmpm** [comment]
resent :)
