### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by cjs1502** [toblum/McLighting#192]
my esp8266 directlty gets connected to my main router,without entering any ssid or password.i want to connect it to my repeater. how can i do that?

**Comment by debsahu** [comment]
In web-browser, go to `http://<IP>/reset_wlan` where `<IP>` is your ESP8266's IP. This will restart the ESP8266 with WiFiManager where you can enter new credentials.

**Comment by cjs1502** [comment]
it worked,thanks a lot,again.
