### ISSUE TITLE
'DynamicJsonDocument' was not declared in this scope

### ISSUE THREAD

**Issue by cjs1502** [toblum/McLighting#197]
In file included from C:\Users\Dell\Downloads\McLighting-master\Arduino\McLighting\McLighting.ino:218:0:

sketch\request_handlers.h: In function 'String listStatusJSON()':

request_handlers.h:281: error: 'DynamicJsonDocument' was not declared in this scope

   DynamicJsonDocument jsonBuffer(bufferSize);

   ^

request_handlers.h:281: error: expected ';' before 'jsonBuffer'

   DynamicJsonDocument jsonBuffer(bufferSize);

                       ^

request_handlers.h:282: error: 'jsonBuffer' was not declared in this scope

   JsonObject& root = jsonBuffer.to<JsonObject>();

                      ^

request_handlers.h:282: error: expected primary-expression before '>' token

   JsonObject& root = jsonBuffer.to<JsonObject>();

                                              ^

request_handlers.h:282: error: expected primary-expression before ')' token

   JsonObject& root = jsonBuffer.to<JsonObject>();

                                                ^

request_handlers.h:294: error: 'serializeJson' was not declared in this scope

   serializeJson(root, json);

                           ^

sketch\request_handlers.h: In function 'String listModesJSON()':

request_handlers.h:306: error: 'DynamicJsonDocument' was not declared in this scope

   DynamicJsonDocument jsonBuffer(bufferSize);

   ^

request_handlers.h:306: error: expected ';' before 'jsonBuffer'

   DynamicJsonDocument jsonBuffer(bufferSize);

                       ^

request_handlers.h:307: error: 'jsonBuffer' was not declared in this scope

   JsonArray& json = jsonBuffer.to<JsonArray>();

                     ^

request_handlers.h:307: error: expected primary-expression before '>' token

   JsonArray& json = jsonBuffer.to<JsonArray>();

                                            ^

request_handlers.h:307: error: expected primary-expression before ')' token

   JsonArray& json = jsonBuffer.to<JsonArray>();

                                              ^

request_handlers.h:316: error: 'serializeJson' was not declared in this scope

   serializeJson(json, json_str);

                               ^

sketch\request_handlers.h: In function 'void sendState()':

request_handlers.h:768: error: 'DynamicJsonDocument' was not declared in this scope

       DynamicJsonDocument jsonBuffer(bufferSize);

       ^

request_handlers.h:768: error: expected ';' before 'jsonBuffer'

       DynamicJsonDocument jsonBuffer(bufferSize);

                           ^

request_handlers.h:769: error: 'jsonBuffer' was not declared in this scope

       JsonObject& root = jsonBuffer.to<JsonObject>();

                          ^

request_handlers.h:769: error: expected primary-expression before '>' token

       JsonObject& root = jsonBuffer.to<JsonObject>();

                                                  ^

request_handlers.h:769: error: expected primary-expression before ')' token

       JsonObject& root = jsonBuffer.to<JsonObject>();

                                                    ^

request_handlers.h:787: error: 'measureJson' was not declared in this scope

       char buffer[measureJson(root) + 1];

                                   ^

request_handlers.h:788: error: 'buffer' was not declared in this scope

       serializeJson(root, buffer, sizeof(buffer));

                           ^

request_handlers.h:788: error: 'serializeJson' was not declared in this scope

       serializeJson(root, buffer, sizeof(buffer));

                                                 ^

sketch\request_handlers.h: In function 'bool processJson(char*)':

request_handlers.h:805: error: 'DynamicJsonDocument' was not declared in this scope

       DynamicJsonDocument jsonBuffer(bufferSize);

       ^

request_handlers.h:805: error: expected ';' before 'jsonBuffer'

       DynamicJsonDocument jsonBuffer(bufferSize);

                           ^

request_handlers.h:806: error: 'DeserializationError' was not declared in this scope

       DeserializationError error = deserializeJson(jsonBuffer, message);

       ^

request_handlers.h:806: error: expected ';' before 'error'

       DeserializationError error = deserializeJson(jsonBuffer, message);

                            ^

request_handlers.h:807: error: 'error' was not declared in this scope

       if (error) {

           ^

request_handlers.h:813: error: 'jsonBuffer' was not declared in this scope

       JsonObject& root = jsonBuffer.as<JsonObject>();

                          ^

request_handlers.h:813: error: expected primary-expression before '>' token

       JsonObject& root = jsonBuffer.as<JsonObject>();

                                                  ^

request_handlers.h:813: error: expected primary-expression before ')' token

       JsonObject& root = jsonBuffer.as<JsonObject>();

                                                    ^

sketch\request_handlers.h: In function 'bool writeConfigFS(bool)':

request_handlers.h:1190: error: 'DynamicJsonDocument' was not declared in this scope

     DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(4));

     ^

request_handlers.h:1190: error: expected ';' before 'jsonBuffer'

     DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(4));

                         ^

request_handlers.h:1191: error: 'jsonBuffer' was not declared in this scope

     JsonObject& json = jsonBuffer.to<JsonObject>();

                        ^

request_handlers.h:1191: error: expected primary-expression before '>' token

     JsonObject& json = jsonBuffer.to<JsonObject>();

                                                ^

request_handlers.h:1191: error: expected primary-expression before ')' token

     JsonObject& json = jsonBuffer.to<JsonObject>();

                                                  ^

request_handlers.h:1201: error: 'serializeJson' was not declared in this scope

     serializeJson(json, DBG_OUTPUT_PORT);

                                        ^

sketch\request_handlers.h: In function 'bool readConfigFS()':

request_handlers.h:1226: error: 'DynamicJsonDocument' was not declared in this scope

       DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(4)+300);

       ^

request_handlers.h:1226: error: expected ';' before 'jsonBuffer'

       DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(4)+300);

                           ^

request_handlers.h:1227: error: 'DeserializationError' was not declared in this scope

       DeserializationError error = deserializeJson(jsonBuffer, buf.get());

       ^

request_handlers.h:1227: error: expected ';' before 'error'

       DeserializationError error = deserializeJson(jsonBuffer, buf.get());

                            ^

request_handlers.h:1229: error: 'error' was not declared in this scope

       if (!error) {

            ^

request_handlers.h:1231: error: 'jsonBuffer' was not declared in this scope

         JsonObject& json = jsonBuffer.as<JsonObject>();

                            ^

request_handlers.h:1231: error: expected primary-expression before '>' token

         JsonObject& json = jsonBuffer.as<JsonObject>();

                                                    ^

request_handlers.h:1231: error: expected primary-expression before ')' token

         JsonObject& json = jsonBuffer.as<JsonObject>();

                                                      ^

request_handlers.h:1232: error: 'serializeJson' was not declared in this scope

         serializeJson(json, DBG_OUTPUT_PORT);

                                            ^

sketch\request_handlers.h: In function 'bool writeStateFS()':

request_handlers.h:1259: error: 'DynamicJsonDocument' was not declared in this scope

   DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(7));

   ^

request_handlers.h:1259: error: expected ';' before 'jsonBuffer'

   DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(7));

                       ^

request_handlers.h:1260: error: 'jsonBuffer' was not declared in this scope

   JsonObject& json = jsonBuffer.to<JsonObject>();

                      ^

request_handlers.h:1260: error: expected primary-expression before '>' token

   JsonObject& json = jsonBuffer.to<JsonObject>();

                                              ^

request_handlers.h:1260: error: expected primary-expression before ')' token

   JsonObject& json = jsonBuffer.to<JsonObject>();

                                                ^

request_handlers.h:1278: error: 'serializeJson' was not declared in this scope

   serializeJson(json, DBG_OUTPUT_PORT);

                                      ^

sketch\request_handlers.h: In function 'bool readStateFS()':

request_handlers.h:1301: error: 'DynamicJsonDocument' was not declared in this scope

       DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(7)+200);

       ^

request_handlers.h:1301: error: expected ';' before 'jsonBuffer'

       DynamicJsonDocument jsonBuffer(JSON_OBJECT_SIZE(7)+200);

                           ^

request_handlers.h:1302: error: 'DeserializationError' was not declared in this scope

       DeserializationError error = deserializeJson(jsonBuffer, buf.get());

       ^

request_handlers.h:1302: error: expected ';' before 'error'

       DeserializationError error = deserializeJson(jsonBuffer, buf.get());

                            ^

request_handlers.h:1303: error: 'error' was not declared in this scope

       if (!error) {

            ^

request_handlers.h:1304: error: 'jsonBuffer' was not declared in this scope

         JsonObject& json = jsonBuffer.as<JsonObject>();

                            ^

request_handlers.h:1304: error: expected primary-expression before '>' token

         JsonObject& json = jsonBuffer.as<JsonObject>();

                                                    ^

request_handlers.h:1304: error: expected primary-expression before ')' token

         JsonObject& json = jsonBuffer.as<JsonObject>();

                                                      ^

request_handlers.h:1305: error: 'serializeJson' was not declared in this scope

         serializeJson(json, DBG_OUTPUT_PORT);

                                            ^

C:\Users\Dell\Downloads\McLighting-master\Arduino\McLighting\McLighting.ino: In lambda function:

McLighting:495: error: 'DynamicJsonDocument' was not declared in this scope

     DynamicJsonDocument jsonBuffer;

     ^

McLighting:495: error: expected ';' before 'jsonBuffer'

     DynamicJsonDocument jsonBuffer;

                         ^

McLighting:496: error: 'jsonBuffer' was not declared in this scope

     JsonObject& json = jsonBuffer.to<JsonObject>();

                        ^

McLighting:496: error: expected primary-expression before '>' token

     JsonObject& json = jsonBuffer.to<JsonObject>();

                                                ^

McLighting:496: error: expected primary-expression before ')' token

     JsonObject& json = jsonBuffer.to<JsonObject>();

                                                  ^

McLighting:553: error: 'serializeJson' was not declared in this scope

     serializeJson(json, json_str);

                                 ^

exit status 1
'DynamicJsonDocument' was not declared in this scope

**Comment by bagotu** [comment]
I have the same problem

**Comment by debsahu** [comment]
@bagotu Please update ArduinoJSON to latest release version: 6.0.1-beta https://github.com/bblanchon/ArduinoJson/releases. There are breaking changes in ArduinoJSON 5.x.x to 6.x.x and not cross-compatible!

**Comment by bagotu** [comment]
Yes of course ArduinoJson by @bblanchon (tested with 6.0.1). I used 6.1.0
now everything worked. Thank you
