### ISSUE TITLE
I have integrated FastLED into your project (among other things)

### ISSUE THREAD

**Issue by russp81** [toblum/McLighting#2]
See here:  https://github.com/russp81/LEDLAMP_FASTLEDs

You did awesome work man, I just like using FastLED better.  Mostly due to my limited skills, and it seems pretty powerful.

I changed the name of the html file because I was using a separate one to make changes / additions to and didn't want to butcher yours.  I am not trying to take credit for any of your work I promise!

Just wanted to let you know...

**Comment by jake-b** [comment]
I have forked russp81's fork at https://github.com/jake-b/Griswold-LED-Controller for those who are interested.  Some code clean-up and improvements.  I intend to use it stand-alone to control my Christmas lights this year.

**Comment by toblum** [comment]
Hi @russp81 and @jake-b ,
I wasn't notified about this issue, so I missed your messages too. Using FastLED was also on my list, so I will definitively have a look into your forked projects. 
Best regards
Tobias
