### ISSUE TITLE
Swapped S and P parameters for /set_brightness

### ISSUE THREAD

**Issue by tnederlof19** [toblum/McLighting#20]
The Wiki of HTTP-REST-API#generic says the following:
Parameter:
c: Value from 0 (off) to 255 (full brightness)
p: Value from 0 (off) to 100 (full brightness)
However, when I send p=100, its not actually set to full brightness. When I send s=100, it does set to full brightness. I assume these values are swapped.

**Comment by toblum** [comment]
I will have a look at it.

**Comment by toblum** [comment]
Dear @tnederlof19,

you're right that was wrong in the documentation. I fixed that.
c = 0-100
p = 0-255
Thank you for reporting this.

Regards
Tobias
