### ISSUE TITLE
'DynamicJsonDocument' was not declared in this scope

### ISSUE THREAD

**Issue by fm14beck** [toblum/McLighting#201]
help me, why after doing the compiler, sketch to issue error. this is my first time trying to learn arduino, please give me enlightenment

**Comment by debsahu** [comment]
Please install ArduinoJSON 6.0.1-beta

**Comment by fm14beck** [comment]
after install ArduinoJSON i get " invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'

what happend

**Comment by debsahu** [comment]
I think you installed ArduinoJSON 6.1.0-beta instead! There are huge breaking change between 6.0.1 and 6.1.0.

**Comment by debsahu** [comment]
As of now, the latest McLighting requires latest ArduinoJSON (6.1.0-beta). Keeping up with the breaking changes is a pain. Closing.
