### ISSUE TITLE
invalid initialization of non-const reference ( jsonObject )

### ISSUE THREAD

**Issue by edyhip** [toblum/McLighting#202]
hello..can u help me fix this
invalid initialization of non-const reference of type
![screenshot 4](https://user-images.githubusercontent.com/41017035/42461613-2225b75e-83cb-11e8-9c5e-ae20d3e42689.png)
thx before...

**Comment by debsahu** [comment]
Please install ArduinoJSON 6.0.1-beta

**Comment by debsahu** [comment]
@toblum let's merge the develop version. So that suck issues don't show up. Breaking changes in ArduinoJSON are a pain.

**Comment by debsahu** [comment]
@edyhip Use the latest version of McLighting and upgrade your Arduino JSON library to ArduinoJSON 6.1.0-beta. Closing.
