### ISSUE TITLE
Using alt 5v (vin) instead of USB for power

### ISSUE THREAD

**Issue by Yohan54** [toblum/McLighting#204]
I have been trying to figure out why the sketch will not work when using this NodeMCU Breakout Board here: https://www.tindie.com/products/bkpsu/nodemcu-breakout-board/. I can use the breakout board on all other sketch's with no issues. I have even loaded the WS2812FX esp8266 web interface and works with breakout board
When I try to use sketch and attach the NodeMCU Lua v3 12-E to the breakout board, I get fast blue blinking led and two leds on strip. At this point, NodeMcu is unresponsive until I remove from breakout board and apply USB power.

**Comment by debsahu** [comment]
What pin are you using in definitions.h?

**Comment by debsahu** [comment]
On second thought, first boot spins up Wifimanager! Have you tried setting the WiFi settings there?

**Comment by Yohan54** [comment]
@debsahu I would do the Wifimanager before putting the NodeMCU in the breakout board. Just let you know, the sketch works when just using jumper wires on NodeMCU pins without breakout board. Like I said before, all other sketch's work when using breakout board except for McLighting and forks of it.

I am using D4 pin (GPIO2)

**Comment by Yohan54** [comment]
@debsahu I did look at other sketch's that work and none of them are using Wifimanager. So, is it possible the Wifimanager the issue. I could exclude it, and just put my ssid/passphrase into sketch.

**Comment by debsahu** [comment]
While connected on your board, could you connect to your computer and check what you see on Serial monitor?

**Comment by Yohan54** [comment]
I get basically nothing, I tried simple commands like help and get nothing back on serial monitor

**Comment by Yohan54** [comment]
Maybe I am missing something on output of serial console, because not getting any output even when not on breakout board. LEDS to light when only using USB power and jumper pins, yes, injecting power to leds if you ask that question.

**Comment by Yohan54** [comment]
@debsahu @toblum I am out of ideas on why McLighting does not work when mounted to the pcb breakout board.
