### ISSUE TITLE
Does not go into AP mode / No Debug Output

### ISSUE THREAD

**Issue by ZeeZeeEff** [toblum/McLighting#21]
Hey,

I do have a problem with your software. When I flash the sketch, the LED's start in rainbow mode but there is no debug output in the serial monitor and the esp does not open an AP. What could be wrong?

Arduino IDE: 1.8.2
all other Libraries are on the same version that you've posted

**Comment by ZeeZeeEff** [comment]
Okay, the issue can be closed!
I solved it by erasing the flash of the esp via esptool

**Comment by ZeeZeeEff** [comment]
I got it to work now, but there is still no Debug output, strange
it is just outputting single blank's

**Comment by toblum** [comment]
Good to hear that it works now. I see from the Gitter chat that debug also works now after erasing flash.

**Comment by dimiHH** [comment]
Hi @ZeeZeeEff , have you figured out what to do about the Serial output? I have the same problem - everything works (ap point, connecting to Wifi, uploading the html file and the webinterface, but I don't get sierial Output. 

I tried different baud rates too.

Thanks,
dimi

**Comment by mogyoros** [comment]
@dimiHH 
For me commenting out the line in McLightning.ino solved the no serial debug issue.
`//  pinMode(BUILTIN_LED, OUTPUT);
`
Cheers,
Tamas

**Comment by toblum** [comment]
Thanks @mogyoros,
yes, that would explain the problem. I wasn't aware of that conflict described here:
https://github.com/esp8266/Arduino/issues/2192

Regards
Tobias
