### ISSUE TITLE
It doesn't remember last effect used when turned off from Home Assistant

### ISSUE THREAD

**Issue by mario-g0** [toblum/McLighting#213]
FIrst of all, thanks for this awesome platform.
But I have a problem: if I turn my lights off from the Home Assistant, when I turn them back on, it doesn't retain the effect I was using before. Is this normal, or can it be corrected?

**Comment by debsahu** [comment]
It is normal, home assistant sends the static effect as default.

**Comment by debsahu** [comment]
Feel free to open if there are any issues / further developments.
