### ISSUE TITLE
On/off button

### ISSUE THREAD

**Issue by cjs1502** [toblum/McLighting#221]
Is there anyway i can use a ttp223 as a switch(D2)? And how can i change the color when triggered?

**Comment by toblum** [comment]
Hi @cjs1502,

I don't have experience with these, but as long as these are just closing the circuit, you can use them with the button setup: https://github.com/toblum/McLighting/wiki/Button-control

Best regards
Tobias

**Comment by cjs1502** [comment]
Ttp223 is a capacitive touch switch,which has 3 pin,one for voltage in,second for i/o and third for ground. What it does it sends signal to i/o pin whenever it is near a conductive surface. But for button in mc lighting you need to make a connection between ground and D2, i haven't found any way to use a capacitive touch switch with it.
If anyone knows please help me.

**Comment by toblum** [comment]
Maybe it's a good idea to also ask at gitter: https://gitter.im/mclighting/Lobby

**Comment by debsahu** [comment]
You can change the way TTP223 responds to a touch. Refer page 4 of the [manual](https://datasheet.lcsc.com/szlcsc/TTP223-BA6_C80757.pdf) to change the output mode. This way you directly connect the output to a digital input on ESP8266. Remember to have common ground.
