### ISSUE TITLE
IoBroker McLighting

### ISSUE THREAD

**Issue by DennisRoschke** [toblum/McLighting#225]
Hi ich finde dein Projekt echt gut , habe auch alles in den IoBroker Integriert nur wie macht mann die anbindung an siri mit yahka zb ich weis nicht wie ich die werte übergeben soll

Vielen dank schonmal.

**Comment by toblum** [comment]
Hallo Dennis,

ich wusste gar nicht, dass eine ioBroker Integration existiert. :-) 
Ich persönlich nutze NodeRed. Am besten du fragst mal beim Autor des Konnektors: https://github.com/instalator/ioBroker.mclighting

Viele Grüße
Tobias
---------------------------------------------
Hello, Dennis,

I didn't know there is an ioBroker integration. :-)
Personally, I use NodeRed. Besster ask the author of the connector: https://github.com/instalator/ioBroker.mclighting

Many greetings
Tobias
