### ISSUE TITLE
00FF00- red   FF0000 -Green other works fine like FFFF00 - yellow 

### ISSUE THREAD

**Issue by sujitrp** [toblum/McLighting#226]
over MQTT  / Wheel / Ring / Node red /Apk  / Openhab

My whole set up is working fine except following issue . 

Red selection reflecting as green over ws2812B
Green selection as red 
Yellow as Yellow 
Blue as Blue 

All effects working fine 
I am using Wemos X- ring . removed the U1 switch . 
Using current version of firmware 
 
This looks my X ring is GRB and not RBG connection Kindly suggest firmware changes to make it compatible with GRB

**Comment by toblum** [comment]
You can change the color setting here:
https://github.com/toblum/McLighting/blob/172d93443d031d89a62b87a874ec712098fd494c/Arduino/McLighting/McLighting.ino#L98 if you're using WS2812FX
or here:
https://github.com/toblum/McLighting/blob/172d93443d031d89a62b87a874ec712098fd494c/Arduino/McLighting/McLighting.ino#L73 if you're using NeoAnimationFX 

Regards
Tobias
