### ISSUE TITLE
Using 12v LEDs

### ISSUE THREAD

**Issue by masterfink** [toblum/McLighting#227]
Is it possible to use this controller with 12V LEDs and a 12V power supply? I have WS2811 strip. I don't want to spend time setting up the 12V LEDs if it's a for sure no, it's not possible.

**Comment by toblum** [comment]
Hi @masterfink,

I have no experience with these. In general all WS2811/12 should work. To handle the 12V you might need to do some level shifting like here: https://randomnerdtutorials.com/10-diy-wifi-rgb-led-mood-light-with-esp8266-step-by-step/ or use a level shifter module.

Regards
Tobias
