### ISSUE TITLE
suggestions for features 

### ISSUE THREAD

**Issue by sujitrp** [toblum/McLighting#228]
1. MQTT Group topic 
2. Mqtt topic to increase by prefix topic or 3 topics. 
3. most important : usage of one node MCU / Wemos Mini  to control multiple rings

**Comment by toblum** [comment]
Hi @sujitrp !

What exactly do you mean wit 1 + 2?
3 was answered here before: https://github.com/toblum/McLighting/issues/118

**Comment by sujitrp** [comment]
2: current MQTT topics are  <Hostname>/in or <Hostname >/Out
    if this chnage to "<Hostname>/<room>/in payload" & "<Hostname>/<room>/out payload"
then using "*/<room>/in payload " one can control group of LED Strip
By increasing the length by one/two Topic multiple groups can be formed.

1: MQTT Group topic (Subscriber) will allow to control the multiple LED Ring / Strip with single MQTT topic (Publisher).  So One can group the strip and control them with single common mqtt topic.

https://community.openhab.org/t/nodemcu-mqtt-led-strip-controller-build-config-how-to-videos/39902

https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview

**Comment by toblum** [comment]
Hi @sujitrp,

ah, now I know. 
I think changing the MQTT structure might disturb the installation of other users, so I have to be careful. I addition the PubSubClient doesn't seem to support wildcard topics for subscription and that seems to be necessary to implement something like this.

Regards
Tobias

**Comment by myk3y** [comment]
Have you considered using fastLED library? It handles multiple strips, many different types of LED and has a huge user base and associated patterns.

https://github.com/FastLED/FastLED
