### ISSUE TITLE
#include<core_esp8266_features>

### ISSUE THREAD

**Issue by gunjanmx4** [toblum/McLighting#23]
how to solve it 
![image](https://user-images.githubusercontent.com/25563672/26939781-07e0273e-4c96-11e7-8a09-2028f1ba7325.png)

**Comment by toblum** [comment]
Hi,

which version of the ESP8266 core for Arduino do you use? Stable or latest?
See: https://github.com/toblum/McLighting/wiki/Software-installation#esp8266-board-support-for-arduino-ide

Regards

**Comment by gunjanmx4** [comment]
thank you sir for your reply sir i am usind esp8266 12-e nodemcu model

**Comment by toblum** [comment]
Dear @gunjanmx4,
thanks. But I was asking for the software version of the ESP Arduino core. Like shown in the attached link.
https://github.com/toblum/McLighting/wiki/Software-installation#esp8266-board-support-for-arduino-ide

Regards
