### ISSUE TITLE
what's wrong? not compiled.

### ISSUE THREAD

**Issue by bagotu** [toblum/McLighting#231]
exit status 1
invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'

**Comment by bagotu** [comment]
I use 6.1.0-beta. But if I use 6.0.1-beta, the sketch is compiled.

**Comment by bagotu** [comment]
any ideas?

**Comment by toblum** [comment]
@bagotu This is definitely related to the version of ArduinoJSON. Could you give the 6.0.1-beta a try?

**Comment by toblum** [comment]
Great! I will have a look at the version issue when I find time.

Regards
Tobias
