### ISSUE TITLE
Possibility to adjust time how long an effect appears and then dissappears

### ISSUE THREAD

**Issue by Hackerboy47** [toblum/McLighting#232]
It would be nice if you could time your effects how long they should appear. 
After the adjusted time they disappear and after pressing the button thez appear again. 
Would be nice for some party lights or party games

**Comment by toblum** [comment]
@Hackerboy47 I think this might make the configuration and code too complex as I try to keep it as simple as possible, but you could achieve this easily if you're using some kind of home automation software like NodeRed or something else that speaks MQTT. Just subscribe to that topic, listen for changes and send a off command after a certain timeout.
