### ISSUE TITLE
Permission to copy the "Software installation" instructions on the Wiki?

### ISSUE THREAD

**Issue by ramapcsx2** [toblum/McLighting#240]
Hi,
this project's Wiki has a great software installation guide that's applicable to my project as well.
I'd like to ask permission to copy the relevant parts to help out users of my project.
Is that okay?

(https://github.com/ramapcsx2/gbs-control)

Best regards
Robert

**Comment by toblum** [comment]
Hi Robert,

that’s okay for me. Feel free to adapt it for your project. 
Nice project by the way. Great to see what the ESP can handle. 

Regards 
Tobias

**Comment by ramapcsx2** [comment]
Awesome!
Thanks for sharing :)
