### ISSUE TITLE
esp8266 crashes when sending ha json

### ISSUE THREAD

**Issue by ryansabin** [toblum/McLighting#244]
I have mosquitto running as my mqtt server. I am trying to send a json command to set the light string. It looks like the esp8266 crashes when I send it. Not sure what the issue is. I can send commands individually to mylight01/in and they work fine. It is just when I try to send the json command.

home/mylight01_ha/state/in
{"state":"ON","color":{"r":50,"g":226,"b":34},"brightness":255,"color_temp":327,"speed":179,"effect":"Static"}

**Comment by debsahu** [comment]
Are you using ArduinoJSON 6.4.0-beta?

**Comment by ryansabin** [comment]
I am using ArduinoJSON 6.4.0-beta.

To clarify why I think it is crashing is that the blue light blinks after
receiving the signal. Then the light strip goes blank for a few seconds
then everything comes back up as it was before.

**Comment by debsahu** [comment]
Do you have access to Serial? It will give more info into this issue. I'll break out my rig to replicate this.

**Comment by ryansabin** [comment]
I do not have anything set up to test a serial connection. Is there another
way I can see what is going on the board?

**Comment by debsahu** [comment]
Subscribe to <hostname>/out MQTT topic. There are birth messages on boot.

**Comment by ryansabin** [comment]
The only response I get is "McLightning ready" when it boots. I can tell it
reboots after sending the json because I get the "McLightning ready"
response a few seconds after sending the command.

**Comment by debsahu** [comment]
Could you change `const size_t bufferSize = JSON_OBJECT_SIZE(3) + JSON_OBJECT_SIZE(5) + 150;` to `const size_t bufferSize = JSON_OBJECT_SIZE(3) + JSON_OBJECT_SIZE(6) + 150;` in processJson function in *request_handlers.h* file and see if this crash happens? It looks like you are trying to send HA commands manually. HA sends {"state":"ON"} seperate from other info, that is why object size is 5. If you are manually sending such data you need such modification.

**Comment by ryansabin** [comment]
I made this change. It still crashes when sending message.I even tried
sending the message on individually and it crashes when receiving just that
message. It also crashes when receiving the other commands minus the ON
command. Not sure what the next steps are. Let me know. Thanks!

**Comment by ryansabin** [comment]
Also, in the Wiki for mclightning on the HA page it shows the "in" topic
containing six objects including the "state".
https://github.com/toblum/McLighting/wiki/Homeassistant-integration

The in-topic consumes JSON formatted data with the following structure:

{
	"brightness": 196,
	"color": {
		"r": 255,
		"g": 100,
		"b": 10
	},
	"speed": 194,
	"color_temp": 24,
	"effect": "Rainbow",
	"state": "ON"
}

**Comment by debsahu** [comment]
It's my oversight in the Wiki. We will change the code to handle 6 objects, but HA does not send data that way. I suggest you to do two things to troubleshoot this, give us output of http://<ip_of_mclighting>/esp_status and get crash dump by following instructions here: https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/stack_dump.html. you will need to access the serial console.

**Comment by ryansabin** [comment]
Here is the info from esp_status. I will get you the crash dump shortly.

{"HOSTNAME":"mylight01","version":"2.1.4","heap":18232,"sketch_size":433584,"free_sketch_space":2711552,"flash_chip_size":4194304,"flash_chip_real_size":4194304,"flash_chip_speed":40000000,"sdk_version":"2.2.1(cfd48f3)","core_version":"2_4_1","cpu_freq":80,"chip_id":1458208,"animation_lib":"WS2812FX","pin":0,"number_leds":512,"button_mode":"ON","amqtt":"ON","home_assistant":"ON","legacy_animations":"ON","esp8266_http_updateserver":"ON","state_save":"SPIFFS"}

**Comment by ryansabin** [comment]
Here is the crash dump with stack trace.

MQTT: Recieved [home/mylight01_ha/state/in]:
{"state":"ON","color":{"r":5,"g":20,"b":119},"brightness":50,"color_temp":327,"speed":121,"effect":"Rainbow"}

Exception (28):
epc1=0x40228052 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000
depc=0x00000000

ctx: sys
sp: 3ffffaf0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffc90:  3fff27c0 0066a7d3 3fff63b4 00000000
3ffffca0:  000000b1 3ffe8308 000000ff 00000000
3ffffcb0:  3fff27c0 3ffffcf4 3ffffcf0 4020ae35
3ffffcc0:  00000000 3fff5f21 00000000 3ffe8540
3ffffcd0:  3ffffcf4 3fff7818 3ffffd08 4022818c
3ffffce0:  3ffffcf4 3fff7818 3ffffd08 4020eb46
3ffffcf0:  6972620a 40107170 22737365 3fff7764
3ffffd00:  000002ac 00000009 3fff7770 3fff7830
3ffffd10:  3fff73fc 00000000 3fff5eb4 3fff5f20
3ffffd20:  0000007d 38307d22 3fff27c0 4021a629
3ffffd30:  3ffffcf4 3ffffd08 3ffffd10 3ffffd40
3ffffd40:  3fff27c0 3fff45bc 00000000 3fff5f21
3ffffd50:  3fff27c0 3fff45bc 3fff5eb4 4020ec9e
3ffffd60:  4022e09b 3fff76f1 3fff7432 4022e0a4
3ffffd70:  00000008 3fff3b84 00000000 00000000
3ffffd80:  3fff76f1 3fff5eac 00000000 402244e2
3ffffd90:  3fff3d0d 00000000 3fff3cd8 40233eb8
3ffffda0:  3fff6124 000000ff 00000000 4021c3a4
3ffffdb0:  0000006d 3fff73fc 00000012 40231991
3ffffdc0:  4020ec40 00000458 402244ec 402244cc
3ffffdd0:  3f000000 3fff6128 402489b3 00000001
3ffffde0:  3fff5eac 3fff45bc 00000000 00000008
3ffffdf0:  3fff2798 000003fa 000003fa 00000000
3ffffe00:  3ffffe70 0000006d 3fff73fc 40224db5
3ffffe10:  0000006d 00000000 0000006d 00000000
3ffffe20:  3fff76d2 0000008c 3fff1c98 4021d5c5
3ffffe30:  0000006d 00000000 0000006d 00000000
3ffffe40:  3fff76d2 0000008c 3fff1c98 4021c199
3ffffe50:  3fff609c 73746867 4021b440 40224d24
3ffffe60:  3fff5dac 00000080 4021b3f4 40224d7c
3ffffe70:  0000001f 0167c323 00000000 4000050c
3ffffe80:  3fff1e19 3fff73fc 3fff3ecc 00000000
3ffffe90:  00000000 00000000 0000001f 00000000
3ffffea0:  3fff1c98 3fff768c 00000000 4021c1cc
3ffffeb0:  40000000 00000030 3fff3b30 4021dc40
3ffffec0:  3fff6124 00000001 00000020 000000fa
3ffffed0:  4022f05c 00000000 0000000e 3fff3b50
3ffffee0:  3fff6124 3fff3b34 3fff3b30 4021dc84
3ffffef0:  3fff6124 3fff3b34 3fff3b35 40230a90
3fffff00:  65fda8c0 000003f7 0000000e 00000000
3fffff10:  00000000 000000c2 3fffff80 3fff76aa
3fffff20:  3fff3cd8 3fff768c 3fff3dc0 402349b9
3fffff30:  00000014 000006c4 000006c4 3fff3cd8
3fffff40:  3fffdc80 3fff427c 3fff73fc 3fff4304
3fffff50:  00000008 3fff3cd8 3fff768c 4022e015
3fffff60:  3fffdc80 3fff427c 3fff73fc 4010453c
3fffff70:  4024c962 3fff427c 3fff73fc 4024c974
3fffff80:  3fff769c 3fff768c 00000000 3fff2890
3fffff90:  4024784f 00000000 3fff73fc 4024e8d3
3fffffa0:  40000f49 3fffdab0 3fffdab0 40000f49
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld
FS File: /config.json, size: 80B
FS File: /index.htm, size: 668.76KB
FS File: /stripstate.json, size: 85B
FS File: /uistate.json, size: 75B
FS Usage: 692258/957314 bytes

Reading config file... Opened!
Config:  Parsed!
{"mqtt_host":"192.168.253.100","mqtt_port":"1883","mqtt_user":"","mqtt_pass":""}WiFiManager
config FS Read success!
*WM: Adding parameter
*WM: host
*WM: Adding parameter
*WM: port
*WM: Adding parameter
*WM: user
*WM: Adding parameter
*WM: pass
*WM:
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result:
*WM: 3
*WM: IP Address:
*WM: 192.168.253.101
SaveConfig is False!
WiFiManager config FS Save failure!
connected...yeey :)
Connecting to MQTT...
Open http://192.168.253.101/ to open McLighting.
Use http://mylight01.local/ when you have Bonjour installed.
New users: Open http://192.168.253.101/upload to upload the webpages first.

Read cfg:
{"mode":1,"strip_mode":2,"brightness":125,"speed":106,"red":19,"green":44,"blue":236}
Success!
*WM: freeing allocated params!
Connected to MQTT.
Session present: 0
Subscribing at QoS 0, packetId: 1
Subscribing at QoS 0, packetId: 2

**Comment by debsahu** [comment]
Please upgrade to latest version of McLighting v2.1.5

**Comment by ryansabin** [comment]
That was it!

Sorry to waste your time. I see now that 2.1.5 fixes a crash in HA color.

Thank you very much

**Comment by debsahu** [comment]
There was a bug with processing brightness in JSON in the previous version.
