### ISSUE TITLE
Turn off BUILT IN LED

### ISSUE THREAD

**Issue by JoJ123** [toblum/McLighting#245]
How can I turn off the BUILTIN_LED?

**Comment by debsahu** [comment]
Set it to an unused pin.

**Comment by JoJ123** [comment]
I set the LED Strip to D4
So f.e. D1 is free, so I change this line:
`#define BUILTIN_LED D1`

But the blue light is still there

**Comment by debsahu** [comment]
Try D6/GPIO12: `#define BUILTIN_LED 12` Or comment out all lines that have BUILTIN_LED in it.

**Comment by JoJ123** [comment]
Both didn't turn the LED off. When I comment everything out, the LED is "blinking"

I have the D1Mini with the ESP8266MOD Module

**Comment by debsahu** [comment]
Ha I figured it out, according to https://wiki.wemos.cc/products:d1:d1_mini your LED pin is on D4. Change the strip connection to another pin to have complete control over BUILTIN_LED. Closing, please reopen if this did not solve your issue.

**Comment by nicoausnrw** [comment]
if the `BUILTIN_LED` set right than you can change in line 477
```
  digitalWrite(BUILTIN_LED, LOW);
```
to

```
  digitalWrite(BUILTIN_LED, HIGH);
```
