### ISSUE TITLE
Use of # in payload turns all lights on

### ISSUE THREAD

**Issue by ryansabin** [toblum/McLighting#248]
This may or may not be an issue. My understanding is that using the # with a hex color in MQTT payload should set the colors of the lights leaving all other settings as is. Where * with a hex color in the payload would set the color and light the lights. If my understanding is correct the "Websocket API" page should state that using # would change the state from OFF to ON. Otherwise, I would prefer to just change the color and not change the state:)

The issue is that the "state" changes from OFF to ON when you change the color using #. Let me know if this is expected.

Here is the initial config of my lights.
"{"state":"OFF","color":{"r":236,"g":33,"b":196},"brightness":245,"color_temp":327,"speed":33,"effect":"Fire Flicker"}"

I change the color using this command as the payload.
#28f31a

Now the HA config of my lights is.
"{"state":"ON","color":{"r":40,"g":243,"b":26},"brightness":245,"color_temp":327,"speed":33,"effect":"Fire Flicker"}"

**Comment by debsahu** [comment]
I see where you are getting at, good catch. It surely is a bug, I'll push the changes to the development branch later today. Will you be able to check?

**Comment by ryansabin** [comment]
Sure. Just let me know when its up.

**Comment by ryansabin** [comment]
Still the same issue. Should you comment out line 414 as well. No reason to
send state at all. It shouldn't change.

**Comment by debsahu** [comment]
If you change the color, HA should reflect the change in color right? We are not toggling stateOn with '#' command.

Quoting your previous example, if your initial state is:
"{"state":"OFF","color":{"r":236,"g":33,"b":196},"brightness":245,"color_temp":327,"speed":33,"effect":"Fire Flicker"}"

I change the color using this command as the payload.
#28f31a

Now the HA config of your lights should be:
"{"state":"OFF","color":{"r":40,"g":243,"b":26},"brightness":245,"color_temp":327,"speed":33,"effect":"Fire Flicker"}"

**Comment by ryansabin** [comment]
That is exactly what happens when you change the color. I have done more
testing. You can see that changing anything actually turns the lights on.
But, the HA state for most of them reports OFF while the lights are really
on. It's weird why changing brightness changes the state. Hopefully this
helps.

"=off"
"{"state":"OFF","color":{"r":213,"g":15,"b":45},"brightness":148,"color_temp":327,"speed":83,"effect":"Theater
Chase"}" *********Lights are off
"?131"
"{"state":"OFF","color":{"r":213,"g":15,"b":45},"brightness":148,"color_temp":327,"speed":131,"effect":"Theater
Chase"}" *********Lights are on
"=off"
"%84"
"{"state":"ON","color":{"r":213,"g":15,"b":45},"brightness":84,"color_temp":327,"speed":131,"effect":"Theater
Chase"}" *********Lights are on. This is the only one that actually reports
lights on.
"=off"
"#1bd311"
"{"state":"OFF","color":{"r":27,"g":211,"b":17},"brightness":84,"color_temp":327,"speed":131,"effect":"Theater
Chase"}" *******Lights are on
