### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by DJSGXII** [toblum/McLighting#25]
I am trying to get this working, but...
When I visit the webaddress the only thing I see is

```
File Not Found

URI: /
Method: GET
Arguments: 0
```

What am I missing?

**Comment by toblum** [comment]
Dear @DJSGXII ,

I think you missed the last step: https://github.com/toblum/McLighting/wiki/Software-installation#upload-the-webpage-to-the-spiffs-filesystem

Regards
Tobias

**Comment by DJSGXII** [comment]
I got it working now. Thanks for making this great project!
