### ISSUE TITLE
mqtt in example

### ISSUE THREAD

**Issue by gent99** [toblum/McLighting#256]
Hi tobi,

could you please post an example for mqtt in? Or tell me, where i could find one? I'd like to use mqttfx to send commands to the topic <CONFIGURED_HOSTNAME>/in

Kind regards

**Comment by debsahu** [comment]
Send any of the commands listed [here](https://github.com/toblum/McLighting/wiki/WebSocket-API) to command your McLighting. Replace **<CONFIGURED_HOSTNAME>** part with the HOSTNAME in definitions.h you configured.

**Comment by gent99** [comment]
thank you, it worked
