### ISSUE TITLE
Button control question

### ISSUE THREAD

**Issue by gent99** [toblum/McLighting#261]
Hi,

this is kind of a "help wanted" issue. I'd like to achieve the following behaviour:
- if longbuttonpress is recognized, then autoparams should be enabled

how can i achieve this?

Kind regards, Holger

**Comment by toblum** [comment]
Hi @gent99,

I didn't try it out but you should have a look at the longKeyPress() function. Replace the contents with a call to handleAutoStart(). That should do the trick.

Regards
Tobias

**Comment by gent99** [comment]
Hi, just to mention: I got it done. Thanks Tobias for the hint.
Kind regards
