### ISSUE TITLE
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

### ISSUE THREAD

**Issue by nguyennamcss** [toblum/McLighting#263]
whenever I try to compile the code and upload it to my nodeMCU it shows this error code. and I am a newbie at this.please help me. Sorry for my weak English.

Error:
Arduino: 1.8.5 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

D:\ESP8266\botton_2\botton_2.ino:88:25: fatal error: SimpleTimer.h: No such file or directory

 #include <SimpleTimer.h>

                         ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by toblum** [comment]
Posted two times
