### ISSUE TITLE
ws2812fx library custom effects

### ISSUE THREAD

**Issue by aidbish** [toblum/McLighting#266]
the ws2812fx has a number of custom effects, how are these added to mclighting,

https://github.com/kitesurfer1404/WS2812FX/tree/master/src/custom

**Comment by toblum** [comment]
Hi @aidbish,

when you implement a custom effect in WS2812FX then it shows up in McLighting. McLIghting always the list of available effects from the used animation library.

Regards
Tobias

**Comment by debsahu** [comment]
Use this [example](https://github.com/kitesurfer1404/WS2812FX/blob/master/examples/ws2812fx_custom_effect2/ws2812fx_custom_effect2.ino). Include appropriate effect header. Add setCustomMode in setup(). That's it, select the custom mode that shows up.

**Comment by aidbish** [comment]
can i include all of the custom effects or only one

**Comment by debsahu** [comment]
I believe upto 4 effects is possible with WS2812FX, haven't tried it yet! I have used only one. You can ask in WS2812FX on how to do it. Also one can add as many custom effects as you want by editing the library as described here: https://github.com/kitesurfer1404/WS2812FX/issues/132

**Comment by aidbish** [comment]
hi guys

any ideas to resolving the issue above

**Comment by moose4lord** [comment]
The setCustomMode() function takes a different form when you have more than one custom effect. You pass a name and mode to the setCustomMode() function, like so:
```c++
uint8_t dualLarsonMode  = ws2812fx.setCustomMode(F("Dual Larson"), dualLarson);
```
The function returns a mode index that you can use in the setSegment() function.

See the ws2812fx_custom_effect2 sketch in the examples folder.
