### ISSUE TITLE
Number of LEDs

### ISSUE THREAD

**Issue by iansexton** [toblum/McLighting#272]
Is there a way of designating the number of LEDs in a strip without recompiling?

**Comment by debsahu** [comment]
Nope

**Comment by iansexton** [comment]
That is a serious limitation :(

**Comment by debsahu** [comment]
@iansexton Try the [develop branch](https://github.com/toblum/McLighting/tree/develop). I made a few modifications to change the number of pixels. One can call for change in number of LEDs by calling: `http://IPADDRESS/pixels?ct=XXX` Need testers!

**Comment by debsahu** [comment]
please see version 2.2.1
