### ISSUE TITLE
auto mode

### ISSUE THREAD

**Issue by batmanvip123** [toblum/McLighting#273]
HI
I need this: when turn on, need to start with auto mode  ?
how?

Thanks

**Comment by toblum** [comment]
HI @batmanvip123,

I didn't try it out, but you can try to call handleAutoStart() at the end of the setup() function.

Regards
Tobias

**Comment by batmanvip123** [comment]
where exactly??
thanks

V V ned., 2. dec. 2018 ob 00:48 je oseba Tobias Blum <
notifications@github.com> napisala:

**Comment by toblum** [comment]
Here: https://github.com/toblum/McLighting/blob/7a44a76aca74d8501f6018c1d9dfc28a43ae45ee/Arduino/McLighting/McLighting.ino#L897

Just try a ittle bit what works best.
