### ISSUE TITLE
Probleme beim Kompilieren

### ISSUE THREAD

**Issue by 4711engel** [toblum/McLighting#274]
Hallo 
Sehr tolles Projekt. 
Leider bekomme ich die INO nicht kompiliert. Ich habe laut Anleitung die libraries geladen. Sind alle im Verzeichnis sichtbar. Trotzdem erhalte ich eine lange Fehlerliste zur Library ArduinoJson, die aber auch im Verzeichnis auftaucht. Vielleicht hat jemand eine Idee. Dann schicke ich mal eine screenshot. 
Hier die ersten Zeilen:
[Fehlermeldung.pdf](https://github.com/toblum/McLighting/files/2636911/Fehlermeldung.pdf)

**Comment by toblum** [comment]
Hallo @4711engel,

welche Version der ArduinoJSON Bibliothek hast du installiert?
Schau hier, welche Versionen du benötigst: https://github.com/toblum/McLighting/wiki/Software-installation

Viele Grüße
Tobias

**Comment by debsahu** [comment]
Only the ino file is present! You will need other files as well.

**Comment by toblum** [comment]
@debsahu Thanks, I missed that in the screenshot.

@4711engel Please copy the whole folder https://github.com/toblum/McLighting/tree/master/Arduino/McLighting including the .h and other .ino files to your PC.

**Comment by toblum** [comment]
Closing issue
