### ISSUE TITLE
Setting color and effect via mqtt (HA)

### ISSUE THREAD

**Issue by gent99** [toblum/McLighting#278]
Hi,

i've got some problems to understand, why this payload (using HA) will not work:

```
{
	"brightness": 196,  
	"color": {  
		"r": 255,
		"g": 0,
		"b": 0 
	},
	"speed": 194,
	"color_temp": 24,
	"effect": "Blink",
	"state": "ON"
}
```

I asume that this should set the strip to blink in red. Instead it's blinking in white. Changing speed seems to work, but not color. Is this a bug or is this unsupported? What else can i do to change the color and the effect via mqtt (in HA mode)?

Kind regards, Holger

**Comment by gent99** [comment]
It seems when omitting the color_temp everything seems to work as expected.

**Comment by debsahu** [comment]
If you are trying to send all the values at the same time in one MQTT message to HA's topic, it will not work. HA sends one value at a time. Could you try that? First state, then color, brightness, mode and speed. Don't send color_temp, it's a shade of white light.

**Comment by gent99** [comment]
Seems to work when omitting color_temp.

I can send
`{
	"brightness": 196,  
	"color": {  
		"r": 255,
		"g": 0,
		"b": 0
	},
	"speed": 196,
	"effect": "Blink",
	"state": "ON"
}`
the strip is blinking red

and then i can send

`{
	"brightness": 196,  
	"color": {  
		"r": 0,
		"g": 255,
		"b": 0
	},
	"speed": 196,
	"effect": "Static",
	"state": "ON"
}`

the strip is blinking green. That's just what i expected and what we want to achieve.

color_temp was the faulty param.

Please close this issue. It's working.

Kind regards, Holger
