### ISSUE TITLE
RGB Colour Order

### ISSUE THREAD

**Issue by maddogs** [toblum/McLighting#282]
Is there any way of changing the colour sequence?

On the colour wheel, when I select Green, I get Blue and Blue is Green

**Comment by debsahu** [comment]
Set your RGB order in code that matches your strip. Edit `WS2812FX strip = WS2812FX(NUMLEDS, PIN, NEO_GRB + NEO_KHZ800);` to `WS2812FX strip = WS2812FX(NUMLEDS, PIN, NEO_BRG + NEO_KHZ800);`

**Comment by maddogs** [comment]
Thanks :) However it is now completely out of order! Red = Blue, Blue = Green, Green = Red

It's not a problem, just thought it would be a easy fix :)

**Comment by maddogs** [comment]
Perfect. Thank you for your help.
