### ISSUE TITLE
Lack of description of the nice outside of the lamp

### ISSUE THREAD

**Issue by cichon** [toblum/McLighting#285]
Can you please provide also a source for the lamp or is it printed? In this case do you can attach a source for the 3D print?

Regards

Waldemar

**Comment by toblum** [comment]
Hi Waldemar,

I think you are talking about the printed lamp from the YouTube video.

It's this model from Thingiverse: https://www.thingiverse.com/thing:1343925 but there are lots of variations of voronoi lamps on the platform.

Regards
Tobias
