### ISSUE TITLE
MCLighting in "accesspoint"

### ISSUE THREAD

**Issue by Xav83130** [toblum/McLighting#29]
Hello,
I have a small question, is it possible to use MCLighting without going through the wifi of my network? (In access point)
If so, how?
thank you in advance.

And congratulations for your code and thank you for sharing.

**Comment by LeonVos** [comment]
And why would you want that ? ☆for if you don't have local wifi, maybe use your phone as A.P. , and then the mclighting and your phone have the same range, and the mclighting server will run. ●i did not tried this, but i think it will work

**Comment by toblum** [comment]
@Xav83130 This is not possible, because McLighting wasn't built this way and would need serious changes to make that work. Using your phone as a AP might be a good workaround as @LeonVos suggested.

**Comment by Xav83130** [comment]
OK thanks a lot
