### ISSUE TITLE
Green and Blue channels backwards

### ISSUE THREAD

**Issue by patrol420** [toblum/McLighting#303]
ws2812b light strip, red is fine but green and blue is backwards. im assuming its because of slight variations in strips? can i swap them in the firmware so the colours come out properly?

**Comment by debsahu** [comment]
In **McLighting.ino**, change `WS2812FX strip = WS2812FX(NUMLEDS, PIN, NEO_GRB + NEO_KHZ800);` to `WS2812FX strip = WS2812FX(NUMLEDS, PIN, NEO_RGB + NEO_KHZ800);`

**Comment by pflaugh** [comment]
This really helped me! Thanks @debsahu.

**Comment by jersam** [comment]
```
// ***************************************************************************
// Load libraries / Instanciate WS2812FX library
// ***************************************************************************
// https://github.com/kitesurfer1404/WS2812FX
#include <WS2812FX.h>
// WS2812FX strip = WS2812FX(NUMLEDS, PIN, NEO_BRG + NEO_KHZ800);
WS2812FX* strip;
```

when I uncomment the fix line I get the following error...


```
exit status 1
'PIN' was not declared in this scope
```

I am using #define USE_WS2812FX_DMA in definitions.h
