### ISSUE TITLE
esp8266WiFi.h

### ISSUE THREAD

**Issue by princlo** [toblum/McLighting#306]
McLighting:6:71: error: ESP8266WiFi.h: No such file or directory

compilation terminated.

exit status 1
ESP8266WiFi.h: No such file or directory

**Comment by princlo** [comment]
i tried including this library from the link given.but i said-
Specified folder/zip file does not contain a valid library

**Comment by debsahu** [comment]
Install ESP8266 Arduino Link: https://github.com/esp8266/Arduino

**Comment by princlo** [comment]
thank you @debsahu i unzipped the file and found the library.

**Comment by debsahu** [comment]
If using Arduino IDE, follow instructions from [here](https://github.com/esp8266/Arduino#installing-with-boards-manager)
