### ISSUE TITLE
Just a flicker on WS set single pixel command

### ISSUE THREAD

**Issue by loucal-sh** [toblum/McLighting#31]
I am not able to control single pixels with commands like !01FF00FF, although I do see a brief flicker.  I have tried different modes although I would expect static to be the correct way to do this.  Can anyone else verify that this isn't just me?

**Comment by toblum** [comment]
Dear @loucal-sh and @andrewbickers,

I found out why this happens and was able to fix it: https://github.com/toblum/McLighting/commit/ae371e08448ffee981a27f899f8083261c27ced4

It's in the latest version.

Regards
Tobias
