### ISSUE TITLE
Node Red Nodes

### ISSUE THREAD

**Issue by ryansabin** [toblum/McLighting#311]
I see in the todo list that you have NodeRed Nodes as the bottom completed task. I have not been able to find any nodes to do with McLighting. Does this just mean that this made possible with MQTT and websockets and a training video. Or is there specific nodes for McLighting.

**Comment by toblum** [comment]
Hi @ryansabin,

there are just a few example nodes available here: https://github.com/toblum/McLighting/tree/master/clients/node_red
Please have also a look here: https://www.youtube.com/watch?v=g3CHtG9c520

Regards
Tobias
