### ISSUE TITLE
Everything work but the NODEMCU is not showing up in the wifi settings

### ISSUE THREAD

**Issue by The1PRimeYT** [toblum/McLighting#314]
Hey i have this issue that my nodemcu is not showing up in my phone seting pls help

**Comment by The1PRimeYT** [comment]
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.86.27
SaveConfig is False!
WiFiManager config FS Save failure!
connected...yeey :)
Open http://192.168.86.27/ to open McLighting.
Use http://LEDs.local/ when you have Bonjour installed.
New users: Open http://192.168.86.27/upload to upload the webpages first.

Couldn't find "/stripstate.json"
 Failure!
*WM: freeing allocated params!

**Comment by toblum** [comment]
HI @The1PRimeYT,

Everything seems to be fine. It already connects to the wifi. Maybe you configured it correctly before.

Just call http://192.168.86.27/upload from your browser and upload the HTML-files as described here: https://github.com/toblum/McLighting/wiki/Software-installation#upload-the-webpage-to-the-spiffs-filesystem

Regards
Tobias
