### ISSUE TITLE
Weird state after power outage

### ISSUE THREAD

**Issue by polachz** [toblum/McLighting#322]
Hallo.

I use your code to drive one led strip used as lamp for my son. I have discovered that when ESP board lost power, and then power is restored, it boots to some weird state, when not all functions work properly. I always get HTTP page, but for example colors doesn't fit where i click in the circle.. Some pre-programed modes doesn't work etc.. This behavior seems to be random. When I re-fash the board, i restore correct functionality... 

I have found in todo-list an Issue

Remove old / wrong EEPROM settings completely [Issue]

Maybe it can be connected with this. Can you be more specific or do you have an idea what can cause this behavior?? I used ESP in several own projects and it boots after power outage to defined state without problems...

**Comment by debsahu** [comment]
By default [`#define ENABLE_STATE_SAVE_SPIFFS`](https://github.com/toblum/McLighting/blob/1578cafbf0aee2cbec9e5e1b76be3a6754072837/Arduino/McLighting/definitions.h#L146) is enabled and state is stored in the SPIFFs and not EEPROM.

Here are my troubleshooting guide,
1. Do a **simple standtest**
```
// Simple NeoPixel test.  Lights just a few pixels at a time so a
// 1m strip can safely be powered from Arduino 5V pin.  Arduino
// may nonetheless hiccup when LEDs are first connected and not
// accept code.  So upload code first, unplug USB, connect pixels
// to GND FIRST, then +5V and digital pin 6, then re-plug USB.
// A working strip will show a few pixels moving down the line,
// cycling between red, green and blue.  If you get no response,
// might be connected to wrong end of strip (the end wires, if
// any, are no indication -- look instead for the data direction
// arrows printed on the strip).

#include <Adafruit_NeoPixel.h>

#define PIN      6
#define N_LEDS 144

Adafruit_NeoPixel strip = Adafruit_NeoPixel(N_LEDS, PIN, NEO_GRB + NEO_KHZ800);

void setup() {
  strip.begin();
}

void loop() {
  chase(strip.Color(255, 0, 0)); // Red
  chase(strip.Color(0, 255, 0)); // Green
  chase(strip.Color(0, 0, 255)); // Blue
}

static void chase(uint32_t c) {
  for(uint16_t i=0; i<strip.numPixels()+4; i++) {
      strip.setPixelColor(i  , c); // Draw new pixel
      strip.setPixelColor(i-4, 0); // Erase pixel a few steps back
      strip.show();
      delay(25);
  }
}
```
2. Is there a common ground? ie ground of ESP8266 connected to ground of ESP8266
3. Attach a 100-1000uF capacitor on the 5V line of LED strip
4. Do you see a color swap? If so change the correct color order by changing the [following line](https://github.com/toblum/McLighting/blob/1578cafbf0aee2cbec9e5e1b76be3a6754072837/Arduino/McLighting/McLighting.ino#L84)
5. Output of http://IPADDRESS/esp_status
6. Provide **Serial output**, if possible
7. Check power supply: do you see a brown-out?

**Comment by debsahu** [comment]
Closing, please reopen if you are still facing issues.
