### ISSUE TITLE
loosing mqtt connection

### ISSUE THREAD

**Issue by patrol420** [toblum/McLighting#323]
so i have 3 node mcu running mclighting powering neopixel strips. worked fine for a few days. now after a day they all drop off mqtt but is still connected to wifi and can control with it via the nodemcus mclighting config screen. have 4 other things reporting to the broker on nodemcus and they work fine. any ideas

**Comment by toblum** [comment]
Can you check if there is any output in the serial console?

Regards
Tobias

**Comment by debsahu** [comment]
Are you using `#define ENABLE_MQTT`? If so, `#define MQTT_MAX_RECONNECT_TRIES 4` defines the number of reconnect tries after which it gives up.

**Comment by debsahu** [comment]
Closing, please reopen if you are still facing issues.
