### ISSUE TITLE
Startup state

### ISSUE THREAD

**Issue by dimitris17563** [toblum/McLighting#324]
Hi Tobias,
I have made your very nice project and i use homeassistant to control and everything works fine. My only problem is that when i reboot the homeassistant the switch is always in off state. Can i do something to read the state of the switch when homeassistant reboots?
Thank you.

Best Regards
Dimitris

**Comment by toblum** [comment]
Hi @dimitris17563,

I don't have any experience with HA. Maybe @debsahu has an ides.

Regards
Tobias

**Comment by debsahu** [comment]
The retain flag is true in or code, so don't know why HA can't read the current state of McLighting. Can you use MQTTfx or something similar to connect to the MQTT server and subscribe to the topics McLighting is sending it's state data on. Upon subscription, if data is retained you should see the values pop up.

**Comment by dimitris17563** [comment]
Thank you for your answer. I am not familiar with MQTT but i will try to do that reading with MQTTfx and i will tell you what i see.

**Comment by dimitris17563** [comment]
I have installed MQTTfx and connected to MQTT server and subscribed to:  home/McLighting01_ha/state/out 
but i didnt see any values to pop up. Only when i turn on and off the switch in homeassistant i see values on state topic.  retain is true in light yaml

**Comment by debsahu** [comment]
Now disconnect and reconnect MQTTfx, resubscribe to that topic. Do you see the values pop in upon subscription?

**Comment by debsahu** [comment]
Also is persistence true for your mosquitto server? https://stackoverflow.com/questions/36126725/how-to-retain-messages-in-mqtt-if-the-mosquitto-broker-goes-down

**Comment by dimitris17563** [comment]
I reconnect to MQTTfx and subscribed but not values pop up. I use the empedded MQTT broker in homeassistant.

**Comment by debsahu** [comment]
It means your MQTT broker does not have persistence turned on! Install mosquito, very light weight and extremely efficient in handing over 100 devices on my network.

**Comment by dimitris17563** [comment]
Ok i will instal mosquito. I have heard of it butas my first step i used the homeassistant;s broker.Thank you very much for your help and congrats for your project.

**Comment by dimitris17563** [comment]
I installed mosquitto and set up it on port 1883 with username : homeassistant and password the same as i had in the internal broker. I dont know what i am doing wrong but i cant see the mqtt entities in homeassistant not the mclighting but also not my sonoff mqtt switches. The mosquito is running and with MQTTfx i see that devices connected to mosquitto too. What do you think?

**Comment by debsahu** [comment]
What does your MQTT setting on HA look like?
```
mqtt:
  broker: IP_ADDRESS_BROKER
```
IP_ADDRESS_BROKER can be localhost opr 127.0.0.1

**Comment by dimitris17563** [comment]
mqtt:
  broker: IP_ADDRESS_BROKER (the same with homeassistant)
  username: homeassistant
  password: mypassword

I left the same settings as the internal MQTT i used before because all my devices have also the same settings.

**Comment by dimitris17563** [comment]
Do i need to make any configuration file in mosquitto folder conf.d ?

**Comment by dimitris17563** [comment]
The broker ip is not local host but 192.168.1.4 (raspberry ip)

**Comment by debsahu** [comment]
yes as per link I set before make sure the file /etc/mosquitto/mosquitto.conf has something similar to
```
persistence true
persistence_file mosquitto.db
persistence_location /var/lib/mosquitto/
```
Again I'm no expert in mosquitto, but I have `allow_anonymous false` on my settings as well

**Comment by dimitris17563** [comment]
Finally i managed to make everything work with mosquitto broker and nginx reverse proxy server (i hadnt setup it correct). So now i restart and mclighting is on the right status! 
Thank you again for your help.

**Comment by debsahu** [comment]
yay!
