### ISSUE TITLE
Accessory HomeKit 

### ISSUE THREAD

**Issue by arturodiazad1** [toblum/McLighting#330]
hello, there is the possibility of creating an accessory for homekit without the need for a homebridge, using the homekit libraries https://github.com/maximkulkin/esp-homekit  from @MaximKulkin for https://github.com/SuperHouse/esp-open-rtos . And it uses the OTA update system Life-Cycle-Manager (LCM) https://github.com/HomeACcessoryKid/life-cycle-manager from @HomeACessoryKid https://github.com/HomeACcessoryKid, just like ravenSystem does https://github.com/RavenSystem/esp-homekit-devices

**Comment by debsahu** [comment]
Unfortunately this code is not written in RTOS manner. I dont have the expertise to do this, don't know about @toblum. It looks like a wontfix label. You can use a $5 RPI0 to emulate a Homebridge. You can use something like https://www.npmjs.com/package/homekit2mqtt to emulate a homebridge based on MQTT topics. I used to use it until HomeAssistant got Homekit plugin.

**Comment by toblum** [comment]
Hi @arturodiazad1,
this functionality would be great to have, but I'm afraid that I'm also not able to rewrite that code so that it fits into McLighting.
But have a look at homekit2mqtt or homebridge. That works quits good.

Regards
Tobias
