### ISSUE TITLE
Visual Studio Code  / PlatformIO  ERROR ✓   I  Like a little help! 

### ISSUE THREAD

**Issue by lampenschakelen** [toblum/McLighting#336]
Hi @toblum Thanks for youtube video: https://youtu.be/7axaXO8cFo8?list=PL3RrveYYJCuRDhrZXcRSQgtsIZ2lH64bv

I am using a Wemos D1 but don't get the WS2812 to work.

https://pastebin.com/nD5184tb 

Here the error: 
![image](https://user-images.githubusercontent.com/26557215/52887935-015aa680-317a-11e9-87a2-85ef55e0f7d7.png)
`
I hope somebody can help me out!

Best Regards, 

Klaas

**Comment by toblum** [comment]
Hi @lampenschakelen,

this shouldn't happen and when I try it out it works without problems. Did you use the latest version from the master branch? Try to call "clean" (bin icon) and recompile using the hook icon.

Regards
Tobias

**Comment by debsahu** [comment]
Looks like you installed VSCode and there is an additional step of installing PlatformIO extension.

**Comment by lampenschakelen** [comment]
Today i did fresh installation on my desktop! It's working without any problems now. 
When i have time i will double check it on my laptop. @toblum Thanks a for making the video. 
@debsahu  i did also the installation of PlatformIO extension.

**Comment by toblum** [comment]
Great! Good to hear.
