### ISSUE TITLE
Wifi not displaying at home

### ISSUE THREAD

**Issue by Sreemagic** [toblum/McLighting#337]
I did full step and upload the code on nodemcu esp8266 from my office pc and its shows shows the wifi deatails while searching. But the issue is if i connect same device at home no wifi is displaying. Even i re uploaded the script from my home using laptop still not working, its shows a message that uploading done. 
Also issue with multi client one library file ArduinoJson, shows not compatible. Installed all the version 5.13(stable)  to latest still same issue

**Comment by debsahu** [comment]
What is your output of serial console? The code tells you the exact version of ArduinoJSON to install. Remove all instances/folders of ArduinoJSON from your libraries folder of Arduino IDE.

**Comment by Sreemagic** [comment]
Thanking you, reinstalled all the software and re uploaded all the code, then its start working
