### ISSUE TITLE
MQTT not working as expected.

### ISSUE THREAD

**Issue by noisufnoc** [toblum/McLighting#34]
After setting MQTT_MAX_PACKET_SIZE to 256 as discovered in https://github.com/toblum/McLighting/issues/30#issuecomment-323892362 I am able to boot and partially connect to my MQTT server...

```
Attempting MQTT connection 1 / 4 ...
MQTT connected!
MQTT topic in: 
MQTT topic out: hostname/out
Attempting MQTT connection 2 / 4 ...
MQTT connected!
MQTT topic in: 
MQTT topic out: hostname/out
Attempting MQTT connection 3 / 4 ...
MQTT connected!
MQTT topic in: 
MQTT topic out: hostname/out
Attempting MQTT connection 4 / 4 ...
MQTT connected!
MQTT topic in: 
MQTT topic out: hostname/out
MQTT connection failed, giving up after 4 tries ...
```

When I subscribe to the hostname/out topic, I see "McLighting ready: hostname", however it never updates nor does publishing messages to hostname/in take any actions.  Assuming things are the same as the WS API, do I just publish =mode, or #HEXRGB?

**Comment by toblum** [comment]
@noisufnoc You're right, the commands are the same as for Websockets and when you have output in hostname/out the it should work.
Do the other protocols work?
It's strange that the in-topic is shown as empty. Could you try to hard-code the intopic in https://github.com/toblum/McLighting/blob/d0ccc58aff2322ef4063818a862c4228842f19a6/Arduino/McLighting/McLighting.ino#L303 Just as a test.
