### ISSUE TITLE
not a issue, mqtt command question

### ISSUE THREAD

**Issue by PhynixP** [toblum/McLighting#343]
Sorry iam very new in MQTT
my first step is via mqtt.fx send a command to my working broker to mclightingv2.
But i have problems to find the command

<CONFIGURED_HOSTNAME>/in<payload>=all
i have test:
LED-Bar/in/command/=all
and a lot of things and i wont work for me

**Comment by PhynixP** [comment]
I have found my error by myself ;)
for all  with the self newby Question:
LED-Bar/in #333333

**Comment by debsahu** [comment]
yes that is correct, replace <CONFIGURED_HOSTNAME> with actual HOSTNAME you have set in definitions.h
