### ISSUE TITLE
Can I controll SK6812 LED Strips?

### ISSUE THREAD

**Issue by gitpower2017** [toblum/McLighting#344]
Hello,

can I controll SK6812 LED Strips?

**Comment by debsahu** [comment]
Are these RGBW version? If so use https://github.com/FabLab-Luenen/McLighting project instead. And if not (ie RGB), they are WS2812B clones so should be fine to use this version of the project.

**Comment by gitpower2017** [comment]
yes this is a RGBW Strip.
I'm Testing the other version.

Gruß & Danke
