### ISSUE TITLE
Manger interface for all ESP 8266 with McLighting or TasmoAdmin to update en find devices

### ISSUE THREAD

**Issue by lampenschakelen** [toblum/McLighting#347]
First of all thanks a lot for making McLighting!

I find this week the TasmoAdmin.  https://github.com/reloxx13/TasmoAdmin
TasmoAdmin (previously SonWEB) is an administrative Website for Devices flashed with Sonoff-Tasmota.
Iam very happy with the easy interface to control and find my devices!! 

Is it possible to make this also work for McLighting? 
I would be great to control and update the device directly from TasmoAdmin administrative Website.

**Comment by toblum** [comment]
@lampenschakelen I don't think we'll have such a sophisticated interface as TasmoAdmin in the near future but I'm looking into surfacing more config options in a new interface. But that will take some time.
