### ISSUE TITLE
[Feature Request] Implementation of Alexa Support with Espalexa Library

### ISSUE THREAD

**Issue by Obicom** [toblum/McLighting#348]
Would it be possible to implement Amazon Alexa support in McLightning with this library? 

https://github.com/Aircoookie/Espalexa?fbclid=IwAR1UeQCERm9MLXv-GLY-qUHAPMObIUAamt16hMnLCWH4_JCnfOb9KGn8Ucs

It looks like most work is done with the library but I am not able to implement by myself with my limited knowledge and weak developer skills.

**Comment by debsahu** [comment]
Maybe you should check WLED project.

**Comment by Obicom** [comment]
I took a look but to be honest I prefer McLightning ... Alexa would be nice to have ... was only an idea ...

**Comment by debsahu** [comment]
Will add to todo list and see if this is feasible.
