### ISSUE TITLE
More than 3 custom effects slots?

### ISSUE THREAD

**Issue by dermodmaster** [toblum/McLighting#355]
Hello, how can I add more buttons for custom effects?

**Comment by debsahu** [comment]
There are only 4 slots for WS2812FX.

https://github.com/toblum/McLighting/blob/93cf8a919fccc262ac3effe59e83f229989d4640/Arduino/McLighting/McLighting.ino#L296

Call strip->setCustomMode(XXX, F("Custom1"), Function) 4 times. Where XXX is 0 or 1 or 2 or 3.

**Comment by dermodmaster** [comment]
Oh well, thank you for quick response.. I asked because I reached the limit ^^ Thought, it was a limit in your repo.
Found https://github.com/kitesurfer1404/WS2812FX/issues/132 where you can modify the library so you can add more slots 👍 
THX for quick response!!!

**Comment by debsahu** [comment]
Yes 4 is a good number and be careful in managing memory with many animations.

**Comment by dermodmaster** [comment]
I'll thx m8 x)
