### ISSUE TITLE
no access point

### ISSUE THREAD

**Issue by richyxi** [toblum/McLighting#358]
hi, i was trying to run the software, everything cool but the thing is that there no access point for me, im not sure if i missing something, somebody can help? 
awsome proyect btw!

**Comment by debsahu** [comment]
I guess you didn't erase flash completely. Your WiFi credentials are stored in a separate place on Flash and can be used to connect to WiFi for following reboots.
![image](https://user-images.githubusercontent.com/24575521/54146142-b98c0f80-4405-11e9-9ab8-950900b946da.png)

**Comment by richyxi** [comment]
Okay, let me try that out men

**Comment by richyxi** [comment]
It worked men, thank u so much.
One little thing, it can work with multiple esp's?

**Comment by debsahu** [comment]
Yes, use different **HOSTNAME** for each esp8266. You can use https://www.youtube.com/watch?v=T1Ul7iN72lI as a reference.
