### ISSUE TITLE
Help!!! Control from the buttons

### ISSUE THREAD

**Issue by Vika1283** [toblum/McLighting#36]
### Please add a programme of control from the buttons 
on/off GPIO5
brightness [-]GPIO6 [+]GPIO7
speed of effect [-]GPIO13 [+]GPIO15
switching of effects GPIO14
auto mode cycle GPIO12
Please help me, I want to do a garland for New Year very much
-------------------------------------------------------------------------------
#include <WS2812FX.h>

#define LED_COUNT 587
#define LED_PIN 2

WS2812FX ws2812fx = WS2812FX(LED_COUNT, LED_PIN, NEO_RGB + NEO_KHZ800);

void setup() {
  ws2812fx.init();
  ws2812fx.setBrightness(255);
  ws2812fx.setSpeed(200);
  ws2812fx.setColor(0x007BFF);
  ws2812fx.setMode(FX_MODE_STATIC);
  ws2812fx.start();
}

void loop() {
  
  ws2812fx.service();
  
}
-------------------------------------------------------------------------------

**Comment by toblum** [comment]
Dear @Vika1283,

thank you for your proposal. I added this to the list of possible enhancements. Maybe you could try to find some help on this in the gitter chat. If there is some code I'd love to integrate this into McLIghting.

Regards
Tobias

**Comment by toblum** [comment]
@Vika1283 There is now button support available: https://github.com/toblum/McLighting/wiki/Button-control
