### ISSUE TITLE
Save the last state?

### ISSUE THREAD

**Issue by moddok** [toblum/McLighting#365]
Hey,

is it somehow possible to save the last state/settings of the LEDs? everytime i power off the arduino (Wemos D1 Mini -> ESP8266) and power it back on again, the LEDs are light up in static red. no settings are saved.
is there something in the code i can change, that the wemos will save the last state?

thank you in advance for your answers!

**Comment by debsahu** [comment]
Last state is stored in SPIFFs, make sure you have correct layout chosen when flashing: 4MB flash, 3MB SPIFFs.

**Comment by moddok** [comment]
thank you! works perfect 💯 👍 
but i have another question: is it somehow possible to deactivate the onboard LED?

**Comment by bpohvoodoo** [comment]
Yes, search for digitalWrite(LED_BUILTIN, LOW) or  digitalWrite(BUILTIN_LED, LOW); in McLighting.ino
and change LOW to HIGH
