### ISSUE TITLE
 pixelconf does not work

### ISSUE THREAD

**Issue by Mezirx** [toblum/McLighting#374]
when I enter:
`http://<ip_module>/pixelconf?ct=300&rgbo=rgb&pin=4`

I get the answer:

> File Not Found
> 
> URI: /pixelconf
> Method: GET
> Arguments: 3
>  ct: 300
>  rgbo: rgb
>  pin: 4

why is it not working?

**Comment by debsahu** [comment]
Which certain are you using? What is your output of `http://<ip_address>/version` use the latest develop branch to test this feature.

**Comment by Mezirx** [comment]
I had a bad version of Mc Light.
I updated to the latest and works.
