### ISSUE TITLE
ESPHome for Hass.io 

### ISSUE THREAD

**Issue by JuniorGamingTime** [toblum/McLighting#378]
Is there a way to have most of the feature from McLighting using ESPHome? I just wanna have eveything running from home assistant (ik there's integration) but I'm really liking how easy it is to edit and upload new code via ESPHome (so after first flash I could just say update code even via my phone. )

**Comment by debsahu** [comment]
Sorry this question is not related to McLighting, but rather ESPHome. Please open an issue with https://github.com/esphome/esphome and ask for features that you want.
