### ISSUE TITLE
are the APA102 also supported?

### ISSUE THREAD

**Issue by salopette** [toblum/McLighting#380]
Thank you for the great project!
I have a question, are the APA102 Leds also supported?
If so, what do I have to change in the config?

Thanks again!

**Comment by toblum** [comment]
HI @salopette,

I'm not sure as I don't own these. 
I'm quite sure that they don't work for standard setups as the Adafruit Neopixel Lib doesn't support them. It might work for setups that use the NeoPixelBus Library (USE_WS2812FX_DMA, USE_WS2812FX_UART) but that's just a guess.
If you could try it out, please drop us a note if it worked.

Regards
Tobias

**Comment by debsahu** [comment]
NeoPixelBus uses DotStarMethod for APA102 on SPI bus with support for both hardware and software SPI methods. Not yet implemented here!

**Comment by toblum** [comment]
I wasn't sure here, thanks for the clarification!

**Comment by salopette** [comment]
so it does not work?

**Comment by salopette** [comment]
https://github.com/Makuna/NeoPixelBus

APA102 - SPI based chipset

**Comment by debsahu** [comment]
I tried and it doesn't work directly. Dotstar/APA102 needs sending of brightness data along with RGB for every LED. I have a different solution, be please be patient until it gets imported here.

**Comment by salopette** [comment]
that would be fantastic, I'm already waiting impatiently!

**Comment by craigsincl** [comment]
Hello, is this still in the pipeline? Thank you for all your hard work on this project.
