### ISSUE TITLE
different speed

### ISSUE THREAD

**Issue by GrumpyNyanCat** [toblum/McLighting#386]
Hello,

I'm running 240 WS2812b @ nodemcu and 120 WS2813 @ wemos d1 mini (both should have the esp8266-12e)

Everything in McLighting is default, except that I had to enable "define USE_WS2812FX_DMA" on the wemos to make the WS2813 work. 

Now my problem ist, that the FX speed of both setups are different from each other. 
For example "Rainbow(11)" is changing the color on the nodemcu(2812b) at 220 speed approximately once every second, but on the wemos(2813) the colors are going crazy, like three times faster. 

It's happening with some animations, but not everyone. The speed of "Blink(1)" and "Breath(2)" for example is on both setups the same.

But there are also animations where it is the opposite like with "Merry Christmas" or "halloween", with this kind of animation the ws2812b setup ist faster ... 

What's happening here?
Is it because of the "define USE_WS2812FX_DMA" or because of the different LED-count?

When I know whats causing this I can maybe use a conversion factor in my script that is controlling both setups to make them the same again. (at least in the speed-range of the slower one)

Thank you very much and have a nice day. (sorry for my english, I'm not a native)

**Comment by debsahu** [comment]
The animation speed is related to the number of LEDs you have and not the method used or type of LED. This project is based on WS2812FX which has all the animations coded in.

**Comment by GrumpyNyanCat** [comment]
ah okay, thank you very much. haha, now I feel a bit stupid. So I have to dive deeper into WS2812FX code to fix this for me.
