### ISSUE TITLE
WLAN Problem & No Controll

### ISSUE THREAD

**Issue by Derodin** [toblum/McLighting#390]
Hello,

I always have the problem that the connection with the WLAN loses and does not reconnect directly.

Where can I enter the wifi data, which he should always use only the one?

/Edit
Also, I have the problem that my strips can no longer control.
At "#define LED_PIN D5" some mode is running and at D4 there is no reaction

**Comment by Derodin** [comment]
Okay, I was able to fix the problem with the controller "#define ENABLE_E131" disabled.

**Comment by debsahu** [comment]
Please reopen if you still facing issues.
