### ISSUE TITLE
5 sec delay in MQTT out

### ISSUE THREAD

**Issue by elle2** [toblum/McLighting#406]
Using McLighting integrated into HomeAssistant, I see a 5 seconds delay between the mqtt command (topic home/HOSTNAME_ha/state/in) sent to ESP8266 and the response (topic home/HOSTNAME_ha/state/out). Regardless this delay in mqtt response, the action (on/off/mode change) is executed in real time on ESP8266. 
Thank you

**Comment by aidbish** [comment]
The delay is intentional. see post 2 from the dev in this thread. https://github.com/toblum/McLighting/issues/398
