### ISSUE TITLE
Setting a Stripe as Matrix

### ISSUE THREAD

**Issue by BigMike71** [toblum/McLighting#409]
Hi, first i must say this is a great project!
ive soldiering an WS2812B stripe on a 75mm tube to build it into an zylinderic Lamp :)
ive now have 8*10 Pixel beginning on top to down and down to top (as Snake). is there an setting for the animations to run perfect on this Matrix?

**Comment by toblum** [comment]
Hi @BigMike71,

I can‘t think of a simple solution. The only option I could think of to Achieve this would be to use E131 protocol and do a mapping in software like it’s explained in this video by @debsahu. https://youtu.be/lZ09GlO2_8s

Regards
Tobias
