### ISSUE TITLE
Request: NTP Function

### ISSUE THREAD

**Issue by Malle355** [toblum/McLighting#41]
Hi,

is it possible to add an NTP (Network Time Protocoll) Function? So that my lights turn on in the evening and turn off in the morning? So you can set the time in the Webinterface.

That would be really awesome.

Thanks.

**Comment by toblum** [comment]
Hi @Malle355 ,

I think this might be possible from the technical side, but would be a big effort. I think this is something that could easily solved by a automation software via MQTT or websocket/REST request. I use NodeRed for such things, but other solutions should work also.

Regards
Tobias

**Comment by Malle355** [comment]
Danke. Ich werde mal schauen ob ich eine Möglichkeit finde.

Von: Tobias Blum [mailto:notifications@github.com]
Gesendet: Freitag, 22. September 2017 17:51
An: toblum/McLighting <McLighting@noreply.github.com>
Cc: Malle355 <marcelseeger1@freenet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [toblum/McLighting] Request: NTP Function (#41)


Hi @Malle355<https://github.com/malle355> ,

I think this might be possible from the technical side, but would be a big effort. I think this is something that could easily solved by a automation software via MQTT or websocket/REST request. I use NodeRed for such things, but other solutions should work also.

Regards
Tobias

**Comment by Malle355** [comment]
Hello,

I just got MQTT working now and its perfectly working with Node-RED. Is it possible to get all the Modes working with MQTT? There are only the Modes which can be requested via Websocket but there are many more on the Mode Site.

[URL=http://www.directupload.net][IMG]http://fs5.directupload.net/images/170927/ah2zsyq3.png[/IMG][/URL]

[URL=http://www.directupload.net][IMG]http://fs5.directupload.net/images/170927/98aeysy8.png[/IMG][/URL]

**Comment by toblum** [comment]
Just have a look here: https://github.com/toblum/McLighting/wiki/WebSocket-API
All Websocket commands (except ~ work). Your could call each animation by /<animation id>, e.g. "/8"
