### ISSUE TITLE
Gradient?

### ISSUE THREAD

**Issue by VeniceNerd** [toblum/McLighting#416]
Is it possible to create gradients with McLighting? I’d love to set saturated blue on one end of my strip and white on the other end with a smooth gradient from one to the other. Is this possible?

If I could  add some subtle pulsing that would be even better!

**Comment by smoochiee** [comment]
agree...some color efrect only rgb..kinda boring..

**Comment by toblum** [comment]
@VeniceNerd Not using the built-in UI as the underlying WS2812FX library does not offer such gradients as a effect. But you may be able to accomplish any pattern using the REST/MQTT/WebService/E131 APIs by adressing each LED separately.
