### ISSUE TITLE
Request: More Modes via MQTT

### ISSUE THREAD

**Issue by Malle355** [toblum/McLighting#42]
Hello,

I just got MQTT working now and its perfectly working with Node-RED. Is it possible to get all the Modes working with MQTT? There are only the Modes which can be requested via Websocket but there are many more on the Mode Site.

![unbenannt](https://user-images.githubusercontent.com/1338236/30931519-3393ad7a-a3c5-11e7-87fd-bb313e9b899c.PNG)

![unbenannt2](https://user-images.githubusercontent.com/1338236/30931520-33abb398-a3c5-11e7-9c1b-facfe4e64bc4.PNG)

Thank you.

**Comment by toblum** [comment]
Just have a look here: https://github.com/toblum/McLighting/wiki/WebSocket-API
All Websocket commands (except ~ work). Your could call each animation by /<animation id>, e.g. "/8"

**Comment by Malle355** [comment]
Ah thanks. Sorry I didn't see that. Thank you that much.
