### ISSUE TITLE
PROGMEM edit is broken

### ISSUE THREAD

**Issue by sehraf** [toblum/McLighting#424]
There are two entries that add an action for `/edit`:
https://github.com/toblum/McLighting/blob/090bddd32b2705f5edb7ec999cb26c50dc470151/Arduino/McLighting/McLighting.ino#L588-L590
vs
https://github.com/toblum/McLighting/blob/090bddd32b2705f5edb7ec999cb26c50dc470151/Arduino/McLighting/McLighting.ino#L682-L690
The first one is deprecated as it cannot handle PROGMEM edit.htm and should be removed.
Currently the first entry is used and this resulting in 404.

**Comment by toblum** [comment]
Hi @sehraf,

thank you for reporting. I'll add that in the next version 2.2.5.

Regards
Tobias

**Comment by toblum** [comment]
@sehraf I just published the new release: https://github.com/toblum/McLighting/releases/tag/v2.2.5
