### ISSUE TITLE
Help with HTTP control in Domoticz

### ISSUE THREAD

**Issue by redfirebrooks** [toblum/McLighting#435]
How do I control my McLighting in Domoticz ?
For example, what command should I enter in domoticz to set the mode BREATH with WHITE color ?

http://IP/tv is OK but http://IP/Breath does not work.

What is the correct syntax ? It is not clear for me in the documentation.

**Comment by jmyrik28** [comment]
http://IPNodemcu/all?rgb=%sFFFFFFF white color all

**Comment by redfirebrooks** [comment]
thanks a lot
