### ISSUE TITLE
Home Assistant MQTT delay

### ISSUE THREAD

**Issue by ambarusa** [toblum/McLighting#437]
Hi! My led ring is working beautifully, thanks to you! I noticed a strange communcation issue between HA and McLighting. The esp is not sending back response to the HA in time. 

If I turn ON the leds from the GUI in HA, it's working, but the switch in the GUI turns back to OFF state, and after a few seconds back to ON. Watching the Serial port I found out that's because the ESP is responding lately, until the response the HA sees the leds turned OFF.

Do you have some ideas how to solve this?

**Comment by ambarusa** [comment]
Other settings, like Brightness, or Color don't make this behaviour.

**Comment by ambarusa** [comment]
https://photos.app.goo.gl/rmNkh8Du2QjnFn6p9 here you can see the issue

**Comment by aidbish** [comment]
its by design, there is a 5 second delay built in for a reason, search for other threads about the reson why
