### ISSUE TITLE
Small note for Hardware wiki page

### ISSUE THREAD

**Issue by deftdawg** [toblum/McLighting#440]
[Public folks can't edit the page directly; so this issue]

Under the second diagram on this page: https://github.com/toblum/McLighting/wiki/Hardware

It might be good to have a quick note that says:

"Note: For circuit layout shown above, LED_PIN in definitions.h must be changed from 14 to 5."

**Comment by toblum** [comment]
Hi @deftdawg,

thank you, I added that.

Regards
Tobias
