### ISSUE TITLE
Red and Green swapped

### ISSUE THREAD

**Issue by Synthron** [toblum/McLighting#469]
Hey,

I'm using the McLighting and just noticed that R and G are swapped. When I turn on the green slider the LEDs go red and vice versa...
I already tried to swap the definitions in the code but that didn't work (lines 822 - 852 in the code).
Any Idea how i can fix that?

**Comment by toblum** [comment]
Hi @Synthron,

your can set the pixelorder via HTTP call: https://github.com/toblum/McLighting/wiki/HTTP-REST-API#get-pixelconf-http10
e.g. /pixelconf?rgbo=rgb
I think GRB is default, so RGB may be the correct choice. Just try it out.

Regards
