### ISSUE TITLE
undefined items

### ISSUE THREAD

**Issue by tzarkyl** [toblum/McLighting#475]
i'm getting errors stating that, byte, boolean, high, uint8_t, uint16_t, uint32_t are undefined
sorry for my ignorance but i expected a drop in solution and just my luck as a zero ability coder it blows up on me.

**Comment by toblum** [comment]
Yeah, that's right. That's actually very ignorant. I think I speak for everyone who's worked on this project in their spare time to build something great. Therefore, I'm afraid I can't help you here. So I'm closing the ticket. I think you understand.
P.S. If you set up the project exactly as instructed, it will work.

Regards
