### ISSUE TITLE
Cant Open/Import McLightingApp.aia

### ISSUE THREAD

**Issue by huge-11** [toblum/McLighting#486]
Hello,
i wanted to check out the McLightingApp on App Inventor but i cant import the aia file. 
Error: The selected project is not a project source file! Project source files are aia files.
And yes i am uploading the aia file. 
Could someone help? 
thanks

**Comment by toblum** [comment]
Hi!
Had no problem to import the file. Used the download button on this page https://github.com/toblum/McLighting/blob/master/clients/Android/McLightningApp.aia to get the .aia file.

**Comment by huge-11** [comment]
Mmmm yes, that it working. I tried downloading the apk and aia files as a zip and some how that is not working. Neither if i save the target on the link, weird.
But thanks
