### ISSUE TITLE
Change Hostname ?

### ISSUE THREAD

**Issue by FraatRamski** [toblum/McLighting#487]
Hallo, 
1st! Very great project!!

I have multiple McLighting now in my network. All have the same Hostname. 
Is there a way to change the hostname?

**Comment by toblum** [comment]
Hi!

You can change the hostname in definitions.h here: https://github.com/toblum/McLighting/blob/eaa9f814d841ff6336f1789ac6e85775514b50ea/Arduino/McLighting/definitions.h#L12
