### ISSUE TITLE
McLighting (esp8266)

### ISSUE THREAD

**Issue by Mikailo09** [toblum/McLighting#494]
Hey, I have problem with McLighting, when I turn on led strip last 15 leds doesn't light up.
Led strip is about 10 meters long and my PSU has enough wattage.
Any ideas where can be problem ?
![IMG_20201206_211655](https://user-images.githubusercontent.com/75585747/101291372-8b20ab80-3808-11eb-9685-9ee846545a23.jpg)

**Comment by toblum** [comment]
Hi @Mikailo09,

did you configure the number of LEDs via /pixelconf?ct=<numberofleds>
Does ist change when you lower the number?

Greetings

**Comment by Mikailo09** [comment]
I edited this and everything is still same.
![Screenshot_2020-12-07-09-14-44-594_name antonsmirnov android arduinodroid2](https://user-images.githubusercontent.com/75585747/101325950-dcfb1d00-386c-11eb-92e4-a792899e21d1.jpg)

**Comment by toblum** [comment]
Modifying the code is only needed for some special cases. 
You could change NUMLEDS easily vis HTTP call as described here: https://github.com/toblum/McLighting/wiki/Software-installation#configure-pin--rgb-mode--numleds-only-for-v221-or-later

**Comment by Mikailo09** [comment]
It works now. Thanks!
