### ISSUE TITLE
Flash Size ESP8266 2.7.4

### ISSUE THREAD

**Issue by mbudde86** [toblum/McLighting#499]
Hi,

I have a problem with the upload of the index.htm, it is apparently not saved.
I am using ESP 8266 2.7.4 in the board manager, which flash size do I have to choose?

![flashsize](https://user-images.githubusercontent.com/10268349/104927965-59bc0380-59a2-11eb-9ead-dad2e202b3e2.jpg)

Thanks for your help, it is a really cool projekt..

**Comment by toblum** [comment]
Hi @mbudde86,

have a look here: https://github.com/toblum/McLighting/wiki/Software-installation#setup-the-arduino-ide

> Set the Flash Size to "4M (1M SPIFFS)". <-- Double check this!

Greetings!
