### ISSUE TITLE
Boot error

### ISSUE THREAD

**Issue by pettib** [toblum/McLighting#5]
Hi
I have been testing this project for a couple of days now but I cant get it working.
I got error message as soon I boot it up. 
No problem to upload sketch but can´t run it.

The error is: ets Jan 8 2013,rst cause:2, boot mode:(2,7) "Even 2,6 and 3,0 sometimes"
I know that this normally i coursed by bad powersupply. But I can run every other sketch i try but not this one. 
Arduino IDE 1.6.13 and 1.6.9
WifiManager 0.11.0 and 0.12.0
ESP8266 2.3.0

Thanks.

**Comment by toblum** [comment]
Hi pettib,
errors in boot sequence are indeed related to powersupply in most cases. Every sketch has another characteristic and may yield different behaviour.

What ESP module do you use and how do you power it?

Regards
Tobias
