### ISSUE TITLE
Instructions please.

### ISSUE THREAD

**Issue by dunk8888** [toblum/McLighting#51]
Hi are there any tutorials on how to get this working? I did use this a few months ago but ive forgoten how to set it up,i remember trying last time and i think i had to use an older version as it was mutch easyer to set up,didnt have to coppy files to spiff.thanks

**Comment by toblum** [comment]
@dunk8888 You find everything here: https://github.com/toblum/McLighting/wiki/Software-installation

The latest version is good to go. The problems with incompatibilities were fixed in the meanwhile. In every version you have to upload the html files after flashing (only the first time).
