### ISSUE TITLE
Why do all LED's get looped through for a single pixel change?

### ISSUE THREAD

**Issue by matjohn2** [toblum/McLighting#57]
I'm not a C (or embedded hardware) developer, so this is potentially a stupid question on it's way;

Why are we looping through all the LED's during `handleSetSingleLED()` as below:

```
    for (uint8_t i = 0; i < strip.numPixels(); i++) {
    strip.setPixelColor(i, ledstates[i].red, ledstates[i].green, ledstates[i].blue);
      //DBG_OUTPUT_PORT.printf("[%u]--[%u] [%u] [%u] [%u] LED index!\n", rgb, i, ledstates[i].red, ledstates[i].green, ledstates[i].blue);
    }
    strip.show();
```
To me, this makes sense included in the `handleSetAllMode()` function, which also has the loop.

I've tried removing it from `handleSetSingleLED()` and replaced it with the following, everything seems to keep working correctly:

```
    strip.setPixelColor(led, ledstates[led].red, ledstates[led].green, ledstates[led].blue);
    strip.show();
```

Am I missing something? the change seems to be standing up to a decent battering via MQTT.

**Comment by toblum** [comment]
Hi @matjohn2,

you're absolutely right. I had something else in mind when I implemented this. The loop is currently not needed and just slows these commands down. I took your proposed change and updated my code.

Thank you for your contribution.

Best regards
Tobias
