### ISSUE TITLE
support for LPD8806

### ISSUE THREAD

**Issue by joseftsch** [toblum/McLighting#58]
Hey,

I own a LED Strip with LPD8806 (like this one https://www.adafruit.com/product/306).
Is this supported by McLightning as well? It has four pins to connect instead of just one "controll pin".

thanks!

**Comment by toblum** [comment]
Hi @joseftsch,

McLighting uses the Adafruit Neopixel Library and unfortunately this doesn't support LPD8806 strips, have a look here: https://learn.adafruit.com/adafruit-neopixel-uberguide/the-magic-of-neopixels

Regards
Tobias
