### ISSUE TITLE
SK6812 compatibility

### ISSUE THREAD

**Issue by semaf** [toblum/McLighting#6]
Would you add compatibility for SK6812 LED String to control the second LED (Warmwhite, Coldwhite)? At least the 4th bit is controlling the second LED.

**Comment by toblum** [comment]
Dear @semaf,

I don't have SK6812 available to try that out, but the neopixel library should support them rudimentary, You'll find some informations here: https://forum.arduino.cc/index.php?topic=364208.0

But maybe you noticed that there are two forks of McLighting that make use of the FastLED library that should support the SK6812 better:
https://github.com/russp81/LEDLAMP_FASTLEDs
and: https://github.com/jake-b/Griswold-LED-Controller

Best reagrds
Tobias
