### ISSUE TITLE
Add On and Off state for MQTT

### ISSUE THREAD

**Issue by AmpacheUser** [toblum/McLighting#62]
It would be nice to be able to get the on or off state of the lights via MQTT.
Have it publish an "on" or "off" state to the /out topic or add a new /state topic.
This is useful for home automation to be able to know the current state of the lights..

**Comment by toblum** [comment]
Hi @AmpacheUser,

there is already the command $ (have a look at https://github.com/toblum/McLighting/wiki/WebSocket-API at the bottom). The data given there should be enough to determine the state.

Regards
Tobias
