### ISSUE TITLE
Multiple device control - ESP-NOW

### ISSUE THREAD

**Issue by a-RN-au-D** [toblum/McLighting#65]
Do you think it would be possible to control multiple devices with a wep app instead of having to change the IP for each?

**Comment by toblum** [comment]
Hi @a-RN-au-D,
this might be possible if you patch the webpage with a possibility to change the target IP. Currently this is not implemented.
If you want to control multiple device and do some automation you could have a look at NodeRed or something similar and use MQTT to control the devices.
Regards
Tobias

**Comment by a-RN-au-D** [comment]
Thanks, I'll look into it :)
