### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by stoehrmark** [toblum/McLighting#69]
After uploading to ESP8266 then reboot and connecting  to WIFI with WiFiManager no problem I get the following
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
File Not Found

URI: /
Method: GET
Arguments: 0
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Have you seen this before?

**Comment by stoehrmark** [comment]
SORRY, I did not follow the WiKi and upload the index.htm file. All good now. EXCELLENT work thank you. My kids are going to love the lamps

Star from Ikea (STRALA)
ESP8266,  WS2812 and very small 5-3.3V power supply inside bubble gum container 
(PS from [http://www.electrodragon.com/product/ac-85-265v-dc-5v-power-module/](url)) Works Great but must add AMS1117 for 3.3V
![img_4919](https://user-images.githubusercontent.com/24501941/34302448-ed434a6a-e6fe-11e7-849d-65499f2968ad.jpg)
![img_4921](https://user-images.githubusercontent.com/24501941/34302449-ed5d19b8-e6fe-11e7-8dd1-37c35097472d.jpg)
![img_4922](https://user-images.githubusercontent.com/24501941/34302450-ed68c11e-e6fe-11e7-820e-f2301077ae4f.jpg)
![img_4924](https://user-images.githubusercontent.com/24501941/34302451-ed76a950-e6fe-11e7-852f-f9f822a265bc.jpg)
![img_4926](https://user-images.githubusercontent.com/24501941/34302452-ed8334fe-e6fe-11e7-9fae-e4fa9ee53337.jpg)
![img_4905](https://user-images.githubusercontent.com/24501941/34302453-ed8f6f94-e6fe-11e7-84ce-33b888b56237.jpg)

**Comment by toblum** [comment]
Great that you figured it out. 
BTW: very nice build. 

Regards
Tobias
