### ISSUE TITLE
Fatal Error: PubSubClient.h: No such file or directory

### ISSUE THREAD

**Issue by petereloaded** [toblum/McLighting#73]
Hey there!
Please help me with the problem, did I do something wrong? How can I solve the problem?

Thanks in advance

Pete

Arduino Error:

C:\Users\*****\Documents\McLighting-master\McLighting-master\Arduino\McLighting\McLighting.ino:29:28: fatal error: PubSubClient.h: No such file or directory

**Comment by toblum** [comment]
Hi Pete,

please have a look at the instructions here:
https://github.com/toblum/McLighting/wiki/Software-installation#used-libraries

Regards
Tobias

**Comment by petereloaded** [comment]
Oh, thx
I have overlooked it :D
Thanks again 

Pete

**Comment by toblum** [comment]
No problem!
