### ISSUE TITLE
NodeMCU random restart..

### ISSUE THREAD

**Issue by athphane** [toblum/McLighting#75]
Has this got anything to do with the McLighting software?
It restarts in the middle of the night and when I wake up it's turned on with the default . I do not want to waste electricity.
10:30PM it restarted.
10:52PM IT RESTARTED AGAIN!!!

**Comment by athphane** [comment]
Never mind.. Should've read the other issues. Feel so stupid..

**Comment by davidblumer** [comment]
What exactly was the problem here? i'm facing the same issues

**Comment by toblum** [comment]
Hi @davidblumer,

In this case I don’t know what’s the issue. But we noticed instabilities with the WS2812FX library in some setups. @debsahus animation library seems not to have these issues. What library are you using?
Also always double check your power supply. 
Regards 
Tobias

**Comment by athphane** [comment]
I started using my lights in May after 4 months of inactivity. Flashed the newest version of McLighting at the time and it is working without a hitch. 
Same NodeMCU board I used months back, No problems since.
