### ISSUE TITLE
Problem z kompilacją

### ISSUE THREAD

**Issue by mlynekg** [toblum/McLighting#78]
Hello, I am new here.
I have a problem with the compilation:

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E module), 80 MHz, 115200, 4M (1M SPIFFS)"

Project options, settings, reload the whole
C: \ Users \ Grzegorz \ Documents \ ArduinoData \ packages \ esp8266 \ tools \ xtensa-lx106-elf-gcc \ 1.20.0-26-gb404fb9-2 / bin / xtensa-lx106-elf-ar: you can not change the name " C: \ Users \ Grzegorz \ AppData \ Local \ Temp \ arduino_build_808509 / arduino.ar "; reason: file exists

completion code 1 Compilation error for the NodeMCU 1.0 board (ESP-12E module).

This report should contain more information in
file -> Contemporary preferences "Show
detailed information during compilation "

How to solve it?

**Comment by toblum** [comment]
Hi @mlynekg,

this may be due to problems with an antivirus software: https://forum.arduino.cc/index.php?topic=86547.0

Regards.
Tobias

**Comment by mlynekg** [comment]
Dziękuję bardzo pomogło wyłączenie programu antywirusowego

Pozdrawiam

Grzegorz
