### ISSUE TITLE
Set hostname for DHCP

### ISSUE THREAD

**Issue by elmicha** [toblum/McLighting#79]
Hi,

thank you for the great firmware!

I found that the supplied DHCP hostname was ESP_XXXX (the mDNS hostname was ok). The browsers on my Android phone don't seem to know about mDNS, so http://mc_lighting.local didn't work.
After seeing https://github.com/tzapu/WiFiManager/issues/208 I tried 

    wifi_station_set_hostname(const_cast<char*>(HOSTNAME));

before the // Setup: WiFiManager comment, and now it request the correct hostname.

**Comment by toblum** [comment]
Hi @elmicha,

thank you for pointing me to this. I added the line to the code.

Regards
Tobias

**Comment by brunoricardojava** [comment]
How do I access the browser? Can be hostname.local?

**Comment by Lehmancreations** [comment]
If you have bonjour installed on your machine and your browser supports it.   I can get to it by hostname.local on my iPhone but not in Firefox.  I’m Firefox I have to find the ip and use that.

**Comment by toblum** [comment]
@brunoricardojava There was a recent fix in McLIghting regarinf MDNS. Make sure to use the latest version.
But there are still some cases where you have to use the IP.
