### ISSUE TITLE
unabe to upload index.htm

### ISSUE THREAD

**Issue by sander816** [toblum/McLighting#82]
i have a esp01, flashing mcligting was pretty easy. I can rech the esp through its ipadress
but when i go to http://ip/upload and upload the index.htm i get a blank page.
When i go back to http://ip  i get the File Not Found again

what am i doing wrong?

**Comment by toblum** [comment]
Hi @sander816,

it looks that the SPIFFS filesystem is not working correctly. That happens sometimes on the ESP01 as the memory is very limited. How did you set the "Flash size" option in Arduino IDE?

Regards
Tobias

**Comment by sander816** [comment]
512k
I selected generic esp8266 module

**Comment by toblum** [comment]
You need to choose a setting that reserves some space for SPIFFS, e.g. 512K (128K SPIFFS).

**Comment by insanity67** [comment]
Same issue here, ESP8266-01 with 1MB Flash. Does not matter what size of SPIFFS I choose, upload is not working. Even reinstalled Arduino IDE (portable), redownloaded all libs and so on. 
Every time File Not Found on / page.

**Comment by insanity67** [comment]
somehow upload "did work", but now I just get random garbage in browser:

`Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 Upgrade- Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 Upgrade- Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 Upgrade- Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/ Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 Upgrade- Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 Upgrade- Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢ Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 Upgrade- Content-Length: 2048 Connection: close ¥¥¥¥¢MD=¥¥¥¥Content-Type: text/html ¥¥¥¥¢[C0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit`

**Comment by insanity67** [comment]
With this tool I was able to upload the index.htm to the SPIFFS filesystem, and its working like a charm:
https://github.com/esp8266/arduino-esp8266fs-plugin

**Comment by toblum** [comment]
Hi @insanity67,

it's unclear why it didn't work the standard way, good to know, that you make it work using the uploader tool!

Regards
Tobias

**Comment by toblum** [comment]
@sander816 Does this work for you also?

**Comment by insanity67** [comment]
Maybe this is an ESP8266-01 problem only.

**Comment by toblum** [comment]
Yes, it looks like it's related to the limited memory on the ESP-01.

**Comment by sander816** [comment]
Yes, but with selecting 64k in arduino
No extra tool needed

**Comment by toblum** [comment]
Thank you for the feedback,. I added that information to the wiki.
