### ISSUE TITLE
Setting single LED issue

### ISSUE THREAD

**Issue by Lehmancreations** [toblum/McLighting#83]
When I try to set a single LED with command !lednumberHEXCODE both with web sockets and MQTT just the first led in the strip lights and it is not the correct color I chose.   No matter what led number I choose it Lights the first one.  If I use +lednumberHEXCODE it works.  I am using an adafruit huzzah and adafruit neopixel 30 led strip. I am using a logic level shifter to convert the 3.3v data pin to 5v data

**Comment by toblum** [comment]
Hi @Lehmancreations,

you're right. The ! command was broken. It' fixed now. Thank you for reporting.

Regards
Tobias
