### ISSUE TITLE
mdns missing addService?

### ISSUE THREAD

**Issue by traveltje2** [toblum/McLighting#85]
Where is the `MDNS.addService("http", "tcp", 80);`  ?
I had to add it after `server.begin();` to get it working correctly while doing `dns-sd -B _http._tcp`.

**Comment by toblum** [comment]
Hi @traveltje2,

yes, you're right, that was missing, I don't know why. But it's fixed now (https://github.com/toblum/McLighting/commit/befcebbe9c1ebbc283a6ba2203900cad07d9b9f8).

Thank you for reporting.

Regards
Tobias
