### ISSUE TITLE
How is the 2 channel coming along

### ISSUE THREAD

**Issue by e11i0t23** [toblum/McLighting#87]
Hi

I would love to be able to split my lights up and them output the same thing to 2 channels is the a way i can ever solder this or software code that you are working that i need to add to get this to work?

Thanks
Elliot

**Comment by toblum** [comment]
Hi Elliot,

support for two or more strips on the same ESP wont came on the short term. This would cause substantial rework of the whole code to support this, also in the UI.

Regards
Tobias

**Comment by LeonVos** [comment]
If you just want to split, you can connect them on the same pin.
