### ISSUE TITLE
Can not be used without internet connection

### ISSUE THREAD

**Issue by szepnorbee** [toblum/McLighting#88]
Without internet connection can not be used because the firmware wait for the wifiManager setup. With wifiManager.setTimeout(180); (3 minutes) can we skip the setup and use the firmware with button control later on? Can this be a feature request? Thx

**Comment by toblum** [comment]
Hi @szepnorbee,

I will have to try that out some time or maybe you can give it a try. I have just added this as a feature request to: https://github.com/toblum/McLighting/blob/master/README.md#todos

Regards
Tobias
