### ISSUE TITLE
Old EEPROM & Flash settings used

### ISSUE THREAD

**Issue by maxledfreak** [toblum/McLighting#92]
Hello,
before installing MCLighting on my node mcu (e12), EasyESP was installed. Settings are saved in EEPROM ans Flash. After flashing MCLighting, the main log in page does not start. 

Proposal for implementing in code: erase flash and EEPROM complete. Then it should works.

greetings
max

**Comment by toblum** [comment]
Hi @maxledfreak,

thank you for your feedback. I will check that, but I'm not sure if that can be accomplished via code. 

Regards
Tobias

**Comment by maxledfreak** [comment]
Hello Tobias,

just have a look in EasyESP Code. It works ;-)

Max

**Comment by toblum** [comment]
Hi,

Thanks, I will have a look at it. I added it to the ToDo list.

Regards
Tobias
