### ISSUE TITLE
MQTT status

### ISSUE THREAD

**Issue by debsahu** [toblum/McLighting#95]
Cant get status of light from MQTT by passing '$' as payload (without the quotes), please help. Trying to integrate with home assistant.

**Comment by debsahu** [comment]
It is an issue with PubSub library, cant seem to send long messages. Please close this issue, thanks!

**Comment by toblum** [comment]
Hi @debsahu,

yes, this could be related to: https://github.com/knolleary/pubsubclient/issues/110
This is something I could not fix in McLighting.

Regards
Tobias
